// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class acct_dtl_tmp2
    {
        public string bank_acct { get; set; }
        public DateTime tran_date { get; set; }
        public string dr_cr { get; set; }
        public decimal amt1 { get; set; }
        public decimal amt2 { get; set; }
        public string dept_no { get; set; }
        public string ccy_type { get; set; }
    }
}