// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class acct_dtl_vlife
    {
        public DateTime tran_date { get; set; }
        public string bank_acct { get; set; }
        public string dr_cr { get; set; }
        public decimal amt { get; set; }
        public string vouno { get; set; }
        public int rowno { get; set; }
        public string ccy_type { get; set; }
    }
}