// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class acct_dtl_bank
    {
        public decimal recno { get; set; }
        public string dept_no { get; set; }
        public DateTime tran_date { get; set; }
        public string bank_acct { get; set; }
        public string ccy_type { get; set; }
        public string dr_cr { get; set; }
        public decimal? fc_amt { get; set; }
        public decimal? ccy_rate { get; set; }
        public decimal amt { get; set; }
        public string type { get; set; }
        public string cash_item { get; set; }
        public string vouno { get; set; }
        public DateTime? ins_date { get; set; }
        public string ins_time { get; set; }
        public string ins_op { get; set; }
        public string memo { get; set; }
        public string memo2 { get; set; }
        public DateTime? deal_date { get; set; }
    }
}