// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class AML_Mapping
    {
        public string Source { get; set; }
        public string code { get; set; }
    }
}