// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class Audit_fx_code_File
    {
        public string item_type { get; set; }
        public string item_code { get; set; }
        public string eng_name { get; set; }
        public string name { get; set; }
        public string class_type { get; set; }
        public string memo { get; set; }
        public int? sort_serial { get; set; }
        public string class_code { get; set; }
        public int? need_check { get; set; }
    }
}