// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class Audit_td_dtl
    {
        public string fund_no { get; set; }
        public string deal_no { get; set; }
        public string dtl_no { get; set; }
        public string bank_acct { get; set; }
        public decimal capital { get; set; }
        public string loan_dept { get; set; }
        public string loan_memo { get; set; }
    }
}