// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class Audit_sk_base
    {
        public string sk_code { get; set; }
        public string sk_name { get; set; }
        public string acccate { get; set; }
        public string sk_type { get; set; }
        public decimal total_share { get; set; }
        public decimal share_list { get; set; }
        public decimal cap_amt { get; set; }
        public DateTime? c_date { get; set; }
        public double cash_dividend { get; set; }
        public DateTime? d_date { get; set; }
        public double stock_dividend { get; set; }
        public double fund_dividend { get; set; }
        public DateTime? p_date { get; set; }
        public double p_dividend { get; set; }
        public decimal p_price { get; set; }
        public decimal eps { get; set; }
        public string buss_type { get; set; }
        public string ccy { get; set; }
        public string tran_out { get; set; }
        public string issue_co { get; set; }
        public int? signet_no { get; set; }
        public decimal? mark_price { get; set; }
        public string is_get_price { get; set; }
        public string UnityID { get; set; }
    }
}