// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class Audit_fn_co
    {
        public string fn_co { get; set; }
        public string co_name { get; set; }
        public string co_s_name { get; set; }
        public string englishname { get; set; }
        public string signature { get; set; }
        public int relationship { get; set; }
        public string unityid { get; set; }
    }
}