// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class Audit_sk_capital
    {
        public DateTime tran_date { get; set; }
        public decimal capital_amt { get; set; }
        public string year_now { get; set; }
    }
}