// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class Audit_sb_broker
    {
        public string broker_co { get; set; }
        public string broker_code { get; set; }
        public string public_code { get; set; }
        public string broker_name { get; set; }
        public string broker_alias { get; set; }
        public string broker_e_name { get; set; }
        public string country_code { get; set; }
        public string zip_code { get; set; }
        public string broker_addr { get; set; }
        public string broker_tel_no { get; set; }
        public string broker_fax { get; set; }
        public int? is_security_broker { get; set; }
        public int? is_bill_broker { get; set; }
        public int? is_bank { get; set; }
        public string broker_account { get; set; }
        public decimal? max_rate { get; set; }
        public string bank_code { get; set; }
        public string bank_account { get; set; }
        public string broker_id { get; set; }
        public string offten_use { get; set; }
    }
}