// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class Audit_code_file
    {
        public string item_type { get; set; }
        public string item_code { get; set; }
        public string description { get; set; }
        public string remark { get; set; }
    }
}