// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class Audit_fund_file
    {
        public string fund_no { get; set; }
        public string fund_name { get; set; }
        public string attitude { get; set; }
        public decimal manage_fee { get; set; }
        public decimal fee { get; set; }
        public string int_type { get; set; }
        public string fee_type { get; set; }
        public DateTime? fee_date { get; set; }
        public DateTime? managefee_date { get; set; }
        public decimal min_manage_fee { get; set; }
        public decimal min_fee { get; set; }
        public string manage_op { get; set; }
        public string acc_op { get; set; }
        public string sk_op { get; set; }
        public string sb_op { get; set; }
        public string sales_op { get; set; }
        public decimal bank_rate { get; set; }
        public string bank_no { get; set; }
        public string branch_no { get; set; }
        public string bank_acct { get; set; }
        public DateTime? start_date { get; set; }
        public DateTime? beg_date { get; set; }
        public DateTime? end_date { get; set; }
        public string _lock { get; set; }
        public int unit_round { get; set; }
        public int nav_round { get; set; }
        public decimal? nav { get; set; }
        public decimal? units { get; set; }
        public string ban { get; set; }
        public short fee_day { get; set; }
        public short int_day { get; set; }
        public decimal stock_rate { get; set; }
        public decimal fee_rate { get; set; }
        public string p_type { get; set; }
        public DateTime? birth_date { get; set; }
        public string charge_man { get; set; }
        public string tel_no_1 { get; set; }
        public string tel_no_2 { get; set; }
        public string fax_no { get; set; }
        public string zip_code_1 { get; set; }
        public string addr1 { get; set; }
        public string zip_code_2 { get; set; }
        public string addr2 { get; set; }
        public DateTime? ins_date { get; set; }
        public string acc_cost { get; set; }
        public string fee_cost { get; set; }
        public string fund_noa { get; set; }
        public string fund_no_vlife { get; set; }
        public string fund_name_vlife { get; set; }
    }
}