// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class Audit_fx_account_file
    {
        public string account { get; set; }
        public string fund_no { get; set; }
        public string fund_name { get; set; }
        public string fund_ename { get; set; }
        public string attitude { get; set; }
        public string acccate { get; set; }
        public string fx_type { get; set; }
        public string bond_kind { get; set; }
        public int? account_seq { get; set; }
        public string ccy_type_base { get; set; }
        public int? roundnum { get; set; }
        public string derivatives { get; set; }
        public string chk_china { get; set; }
        public string chk_taiwan { get; set; }
    }
}