// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class Audit_bd_ex_rate
    {
        public DateTime tran_date { get; set; }
        public string ccy_type { get; set; }
        public decimal ccy_rate { get; set; }
    }
}