// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bank_acct_agent
    {
        public DateTime tran_date { get; set; }
        public string emp_id { get; set; }
        public string bank_acct { get; set; }
        public int tran_type { get; set; }
        public string agent_emp { get; set; }
    }
}