// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bank_temp_trans_log
    {
        public DateTime tran_date { get; set; }
        public string bank_name { get; set; }
        public string bank_acct { get; set; }
        public string ccy_type { get; set; }
        public string acct_memo { get; set; }
        public decimal bk_dendbal { get; set; }
        public decimal acct_dendbal { get; set; }
        public decimal temp_amt { get; set; }
        public int err_no { get; set; }
        public string err_memo { get; set; }
        public string op_name { get; set; }
        public string file_name { get; set; }
        public int _checked { get; set; }
    }
}