// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bank_base
    {
        public string bank_no { get; set; }
        public string branch_no { get; set; }
        public string bank_name { get; set; }
        public int seq_no { get; set; }
        public int fee_type1 { get; set; }
        public int fee_type2 { get; set; }
        public string bank_l_name { get; set; }
        public string bank_e_name { get; set; }
        public string swift_code { get; set; }
        public string head_office_name { get; set; }
        public string head_office_registration { get; set; }
        public string head_office_taxID { get; set; }
        public bool head_office_disable { get; set; }
        public string head_office_representative { get; set; }
        public string rep_SEX { get; set; }
        public string rep_english_name { get; set; }
        public string rep_nationality { get; set; }
        public string branch_name { get; set; }
        public string branch_registration { get; set; }
        public bool branch_disable { get; set; }
        public DateTime AML_scan_dt { get; set; }
        public string AML_mail { get; set; }
        public string loguser { get; set; }
        public DateTime logtime { get; set; }
    }
}