// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bank_inout_dtl
    {
        public DateTime tran_date { get; set; }
        public string acct_out { get; set; }
        public string ccy_type { get; set; }
        public string acct_in { get; set; }
        public int seq_no { get; set; }
        public decimal amt { get; set; }
        public decimal fee { get; set; }
        public decimal net { get; set; }
        public string pay_type { get; set; }
        public string sub_type { get; set; }
        public string rec_status { get; set; }
        public decimal mark_no { get; set; }
        public int marked { get; set; }
        public string bill_no { get; set; }
        public decimal fc_amt { get; set; }
        public decimal fc_fee { get; set; }
        public decimal fc_net { get; set; }
        public decimal ccy_rate { get; set; }
        public DateTime? settle_date { get; set; }
        public int fedi_deal { get; set; }
        public int data_tp { get; set; }
    }
}