// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bank_temp_trans
    {
        public decimal recno { get; set; }
        public DateTime tran_date { get; set; }
        public string bank_acct { get; set; }
        public string ccy_type { get; set; }
        public string dr_cr { get; set; }
        public decimal amt { get; set; }
        public int seq_no { get; set; }
        public string rec_status { get; set; }
    }
}