// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bank_disk_l
    {
        public DateTime tran_date { get; set; }
        public string bank_acct { get; set; }
        public string dr_cr { get; set; }
        public decimal amt { get; set; }
        public string memo1 { get; set; }
        public string memo2 { get; set; }
        public int _checked { get; set; }
        public decimal seqno { get; set; }
        public DateTime? checked_date { get; set; }
    }
}