// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bank_account
    {
        /// <summary>
        /// 銀行代號
        /// </summary>
        public string bank_code { get; set; }
        /// <summary>
        /// 銀行帳號
        /// </summary>
        public string bank_account1 { get; set; }
        public string account_name { get; set; }
        /// <summary>
        /// 幣別
        /// </summary>
        public string ccy { get; set; }
        /// <summary>
        /// 開戶日期
        /// </summary>
        public DateTime? creat_date { get; set; }
        /// <summary>
        /// 銷戶日期
        /// </summary>
        public DateTime? destroy_date { get; set; }
        /// <summary>
        /// 使用狀態
        /// </summary>
        public string status { get; set; }
        /// <summary>
        /// 帳戶類別
        /// </summary>
        public string kind { get; set; }
    }
}