// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bank_int
    {
        public string bank_acct { get; set; }
        public string ccy_type { get; set; }
        public int int_year { get; set; }
        public int int_month { get; set; }
        public DateTime rec_date { get; set; }
        public DateTime? acc_date { get; set; }
        public decimal total_int { get; set; }
        public decimal tax { get; set; }
        public decimal net { get; set; }
        public string memo { get; set; }
        public decimal seqno { get; set; }
        public decimal ccy_rate { get; set; }
        public decimal fc_total_int { get; set; }
        public decimal fc_tax { get; set; }
        public decimal fc_net { get; set; }
    }
}