// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bank_endbal
    {
        public string bank_no { get; set; }
        public string branch_no { get; set; }
        public string act_type { get; set; }
        public string ccy_type { get; set; }
        public int share_acct { get; set; }
        public int policy_acct { get; set; }
        public int seq_no { get; set; }
        public string bank_acct { get; set; }
        public decimal fc_dendbal { get; set; }
        public decimal cost_rate { get; set; }
        public decimal dendbal { get; set; }
        public decimal fc_dr_amt { get; set; }
        public decimal fc_cr_amt { get; set; }
        public decimal dr_amt { get; set; }
        public decimal cr_amt { get; set; }
        public DateTime tran_date { get; set; }
        public decimal acct_rate { get; set; }
        public decimal acct_int { get; set; }
        public decimal temp_dendbal { get; set; }
        public int oiu_acct { get; set; }
    }
}