// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bank_acct_predesign
    {
        public string bank_acct { get; set; }
        public string bank_acct2 { get; set; }
        public string predesign_bank_no { get; set; }
        public string predesign_branch_no { get; set; }
        public string predesign_account { get; set; }
        public string predesign_title { get; set; }
        public string memo { get; set; }
    }
}