// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bank_acct_limit
    {
        public string bank_acct { get; set; }
        public string ccy_type { get; set; }
        public decimal limit_amt { get; set; }
    }
}