// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bank_base_aml_nation
    {
        public string Nation_Nm { get; set; }
        public string Nation_ENNm { get; set; }
        public string Nation_ISO_Cd { get; set; }
    }
}