// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bd_bdr002d
    {
        public string fund_no { get; set; }
        public string fund_name { get; set; }
        public DateTime tran_date { get; set; }
        public string acccate { get; set; }
        public string bond_kind { get; set; }
        public string kind_name { get; set; }
        public string bond_no { get; set; }
        public string bond_name { get; set; }
        public decimal? last_month { get; set; }
        public decimal? interest { get; set; }
        public decimal? buy_int { get; set; }
        public decimal? sell_int { get; set; }
        public decimal? own_int { get; set; }
        public decimal? tan_net { get; set; }
        public decimal? all_interest { get; set; }
        public string month_di { get; set; }
        public decimal? tan_net_this_month { get; set; }
        public decimal? tan_net_last_month { get; set; }
        public decimal? tan_net_rec { get; set; }
        public decimal? tan_net_sell { get; set; }
        public decimal? tan_net_change { get; set; }
        public string ccy_type_tf { get; set; }
    }
}