// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bd_base
    {
        /// <summary>
        /// 債券編號
        /// </summary>
        public string bond_no { get; set; }
        /// <summary>
        /// 債券類別(code_file.item_type=&apos;B1&apos;)
        /// </summary>
        public string bond_kind { get; set; }
        /// <summary>
        /// 擔保類別(code_file.item_type=&apos;B2&apos;)
        /// </summary>
        public string insure_type { get; set; }
        /// <summary>
        /// 債券簡稱
        /// </summary>
        public string bond_alias { get; set; }
        /// <summary>
        /// 債券名稱
        /// </summary>
        public string bond_name { get; set; }
        /// <summary>
        /// 發行公司(bd_issueco.issue_co)
        /// </summary>
        public string issue_co { get; set; }
        /// <summary>
        /// 發行日期
        /// </summary>
        public DateTime issue_date { get; set; }
        /// <summary>
        /// 發行期間
        /// </summary>
        public decimal issue_period { get; set; }
        /// <summary>
        /// 發行金額
        /// </summary>
        public decimal issue_amt { get; set; }
        /// <summary>
        /// 到期日期
        /// </summary>
        public DateTime maturity_date { get; set; }
        /// <summary>
        /// 票面利率
        /// </summary>
        public double coupon_rate { get; set; }
        /// <summary>
        /// 每年領息次數
        /// </summary>
        public short int_times { get; set; }
        /// <summary>
        /// 每年複利次數
        /// </summary>
        public short double_int_times { get; set; }
        /// <summary>
        /// 還本方式(code_file.item_type=&apos;B3&apos;)
        /// </summary>
        public string capital_type { get; set; }
        /// <summary>
        /// 第幾年開始還本
        /// </summary>
        public double? capital_year { get; set; }
        /// <summary>
        /// 每幾年還本一次
        /// </summary>
        public double? capital_step { get; set; }
        /// <summary>
        /// 還本比率
        /// </summary>
        public short? capital_part { get; set; }
        public string int_date { get; set; }
        /// <summary>
        /// 擔保機構
        /// </summary>
        public string insure_name { get; set; }
        /// <summary>
        /// 是否為主順位(1.主順位 2.次順位)
        /// </summary>
        public string main_order { get; set; }
        public string sk_code { get; set; }
        public string tax_type { get; set; }
        public string bond_no2 { get; set; }
        public decimal? tax_rate { get; set; }
        public string bond_no3 { get; set; }
        public string cancel_type { get; set; }
        public int? signetno { get; set; }
        public string bond_name2 { get; set; }
        public string bond_kind2 { get; set; }
        public string tran_type { get; set; }
        public string remark { get; set; }
        public string period_type { get; set; }
        public string rate_type { get; set; }
        public string int_date_first { get; set; }
        public string acccate { get; set; }
        public string unityid { get; set; }
        public string trade_market { get; set; }
        public string ccy_type { get; set; }
        public string div_type { get; set; }
    }
}