// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bd_changefund
    {
        public DateTime tran_date { get; set; }
        public string fund_no { get; set; }
        public string bond_no { get; set; }
        public string cancel_type { get; set; }
        public string deal_no { get; set; }
        public string acccate { get; set; }
        public decimal? fund_cost { get; set; }
        public string new_deal_no { get; set; }
        public string new_acccate { get; set; }
        public string new_fund_no { get; set; }
        public decimal? new_fund_cost { get; set; }
        public decimal? change_tan_net { get; set; }
    }
}