// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bd_cash
    {
        /// <summary>
        /// 債券編號
        /// </summary>
        public string bond_no { get; set; }
        /// <summary>
        /// 還本領息日
        /// </summary>
        public DateTime pay_date { get; set; }
        /// <summary>
        /// 領息金額
        /// </summary>
        public decimal i_amt { get; set; }
        /// <summary>
        /// 還本金額
        /// </summary>
        public decimal c_amt { get; set; }
        /// <summary>
        /// 賸餘本金
        /// </summary>
        public decimal m_amt { get; set; }
    }
}