// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bd_change
    {
        /// <summary>
        /// 1&gt;&gt;010用，2&gt;&gt;012用
        /// </summary>
        public string action { get; set; }
        /// <summary>
        /// 1 表示 從broker_code&gt;&gt;broker_code2.....2表示從broker_code2&gt;&gt;broker_code
        /// </summary>
        public decimal action_type { get; set; }
        public string fund_no { get; set; }
        public string broker_code { get; set; }
        public DateTime tran_date { get; set; }
        public string bond_no { get; set; }
        public decimal par_value { get; set; }
        public decimal? sheet { get; set; }
        public decimal? sheet_value { get; set; }
        public string save_model { get; set; }
        public string save_type { get; set; }
        public string broker_code2 { get; set; }
        public decimal? amount { get; set; }
        public string rec_status { get; set; }
        public string tran_no { get; set; }
        public string save_model1 { get; set; }
        public string save_type1 { get; set; }
    }
}