// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bd_chgtype
    {
        /// <summary>
        /// 基金代號
        /// </summary>
        public string fund_no { get; set; }
        /// <summary>
        /// 舊債券編號
        /// </summary>
        public string bond_no_old { get; set; }
        /// <summary>
        /// 新債券編號
        /// </summary>
        public string bond_no_new { get; set; }
        /// <summary>
        /// 改型日期
        /// </summary>
        public DateTime change_date { get; set; }
        /// <summary>
        /// 改型說明
        /// </summary>
        public string change_type { get; set; }
        /// <summary>
        /// 改型面額
        /// </summary>
        public decimal par_value { get; set; }
        /// <summary>
        /// 改型成本
        /// </summary>
        public decimal cost { get; set; }
        /// <summary>
        /// 改型前手息
        /// </summary>
        public decimal bef_int { get; set; }
        public decimal? accrued_tax { get; set; }
        public decimal? before_tax { get; set; }
    }
}