// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bd_exclude_list
    {
        public DateTime exclude_date { get; set; }
        public string deal_no { get; set; }
    }
}