// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bd_issueco
    {
        public string issue_co { get; set; }
        public string issue_name { get; set; }
        public string sk_code { get; set; }
        public decimal guarantee { get; set; }
        public decimal no_guarantee { get; set; }
        public decimal? no_guarantee1 { get; set; }
        public decimal? no_guarantee2 { get; set; }
        public decimal? total { get; set; }
        public string issue_type { get; set; }
        public string UnityID { get; set; }
        public string bank_no { get; set; }
    }
}