// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bd_list_bk_A03106
    {
        public string fund_no { get; set; }
        public string deal_no { get; set; }
        public string broker_code { get; set; }
        public DateTime tran_date { get; set; }
        public DateTime? settle_date { get; set; }
        public string bond_no { get; set; }
        public decimal par_value { get; set; }
        public decimal net { get; set; }
        public decimal? par_value2 { get; set; }
        public decimal? net2 { get; set; }
        public string deal_no_old { get; set; }
        public decimal? tan_net { get; set; }
        public decimal? fund_int { get; set; }
        public string acccate { get; set; }
        public decimal par_value_ntd { get; set; }
        public decimal net_ntd { get; set; }
        public decimal? par_value2_ntd { get; set; }
        public decimal? net2_ntd { get; set; }
        public decimal? tan_net_ntd { get; set; }
        public decimal? fund_int_ntd { get; set; }
    }
}