// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bd_newdeal
    {
        public string deal_no { get; set; }
        public string deal_no_new { get; set; }
        public string action { get; set; }
    }
}