// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bd_price
    {
        public string bond_no { get; set; }
        public DateTime tran_date { get; set; }
        public decimal unit_price { get; set; }
        public decimal seq_no { get; set; }
        public string sys_no { get; set; }
    }
}