// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bd_reccash_trans
    {
        public string fund_no { get; set; }
        public string bond_no { get; set; }
        public string bond_kind { get; set; }
        public string deal_no { get; set; }
        public string acccate { get; set; }
        public DateTime tran_date { get; set; }
        public DateTime pay_date { get; set; }
        public DateTime rec_date { get; set; }
        public decimal par_value { get; set; }
        public decimal rec_cap { get; set; }
        public decimal rec_cost { get; set; }
        public decimal rec_int { get; set; }
        public decimal tax1 { get; set; }
        public decimal tax2 { get; set; }
        public decimal fee { get; set; }
        public decimal tan_net { get; set; }
        public decimal co_value { get; set; }
        public decimal rec_cap_benfit { get; set; }
        public decimal serial { get; set; }
        public decimal ccy_rate { get; set; }
        public decimal par_value_ntd { get; set; }
        public decimal rec_cap_ntd { get; set; }
        public decimal rec_cost_ntd { get; set; }
        public decimal rec_int_ntd { get; set; }
        public decimal tax1_ntd { get; set; }
        public decimal tax2_ntd { get; set; }
        public decimal fee_ntd { get; set; }
        public decimal tan_net_ntd { get; set; }
        public decimal co_value_ntd { get; set; }
        public decimal rec_cap_benfit_ntd { get; set; }
    }
}