// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bd_reccash
    {
        public string fund_no { get; set; }
        public string bond_no { get; set; }
        public DateTime pay_date { get; set; }
        public double org_parvalue { get; set; }
        public double par_value { get; set; }
        public double cost { get; set; }
        public double rec_cap { get; set; }
        public double rec_cost { get; set; }
        public double rec_int { get; set; }
        public double rec_tax { get; set; }
        public double rec_net { get; set; }
        public double bef_int { get; set; }
        public DateTime rec_date { get; set; }
        public string broker_code { get; set; }
        public decimal? accrued_tax { get; set; }
        public decimal? before_tax { get; set; }
        public string pay_type { get; set; }
        public string account { get; set; }
        public decimal? o_amt { get; set; }
        public string rec_status { get; set; }
        public string save_model { get; set; }
        public string save_type { get; set; }
        public string broker_code2 { get; set; }
        public decimal? rec_cap_benfit { get; set; }
        public decimal? tan_net { get; set; }
        public decimal? rec_cocost01 { get; set; }
        public decimal? rec_cocost02 { get; set; }
        public DateTime? end_date { get; set; }
        public decimal serial { get; set; }
        public decimal ccy_rate { get; set; }
        public double org_parvalue_ntd { get; set; }
        public double par_value_ntd { get; set; }
        public double cost_ntd { get; set; }
        public double rec_cap_ntd { get; set; }
        public double rec_cost_ntd { get; set; }
        public double rec_int_ntd { get; set; }
        public double rec_tax_ntd { get; set; }
        public double rec_net_ntd { get; set; }
        public double bef_int_ntd { get; set; }
        public decimal? accrued_tax_ntd { get; set; }
        public decimal? before_tax_ntd { get; set; }
        public decimal? o_amt_ntd { get; set; }
        public decimal? rec_cap_benfit_ntd { get; set; }
        public decimal? tan_net_ntd { get; set; }
        public decimal? rec_cocost01_ntd { get; set; }
        public decimal? rec_cocost02_ntd { get; set; }
    }
}