// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bd_sheet_trans_hist
    {
        public string fund_no { get; set; }
        public string deal_no_sheet { get; set; }
        public string bond_no { get; set; }
        public DateTime tran_date { get; set; }
        public decimal par_value_sheet { get; set; }
        public decimal sheet { get; set; }
        public string buysell_opt { get; set; }
        public string action_type { get; set; }
    }
}