// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bd_tmpbdr23
    {
        public string userid { get; set; }
        public string fund_no { get; set; }
        public string bond_no { get; set; }
        public string bond_name { get; set; }
        public DateTime? maturity_date { get; set; }
        public decimal? coupon_rate { get; set; }
        public decimal? p1 { get; set; }
        public decimal? p2 { get; set; }
        public decimal? p3 { get; set; }
        public decimal? p4 { get; set; }
        public decimal? p5 { get; set; }
        public decimal? p6 { get; set; }
        public string broker_code { get; set; }
    }
}