// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bd_transtempCB
    {
        public string fund_no { get; set; }
        public string deal_no { get; set; }
        public string broker_code { get; set; }
        public DateTime tran_date { get; set; }
        public string bond_no { get; set; }
        public decimal par_value { get; set; }
        public decimal unit_price { get; set; }
        public decimal yield { get; set; }
        public decimal amount { get; set; }
        public decimal interest { get; set; }
        public decimal broker_comm { get; set; }
        public decimal trans_tax { get; set; }
        public decimal net { get; set; }
        public decimal fund_cost { get; set; }
        public decimal fund_int { get; set; }
        public string action { get; set; }
        public string org_deal_no { get; set; }
        public decimal volumns { get; set; }
        public decimal before_tax { get; set; }
        public decimal? real_rate { get; set; }
        public string cancel_type { get; set; }
        public DateTime? settle_date { get; set; }
        public decimal? co_cost { get; set; }
        public string acccate { get; set; }
        public decimal opt_premuim { get; set; }
    }
}