// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bd_total
    {
        /// <summary>
        /// 基金代號(fund_file.fund_no)
        /// </summary>
        public string fund_no { get; set; }
        /// <summary>
        /// 債券編號(bd_base.bond_no)
        /// </summary>
        public string bond_no { get; set; }
        public decimal par_value_deal { get; set; }
        /// <summary>
        /// 現存面額
        /// </summary>
        public decimal par_value { get; set; }
        public decimal bef_int { get; set; }
        /// <summary>
        /// 現存成本
        /// </summary>
        public decimal net { get; set; }
        /// <summary>
        /// 庫存日期
        /// </summary>
        public DateTime tran_date { get; set; }
        public decimal before_tax { get; set; }
        public string deal_no { get; set; }
        public decimal net2_deal { get; set; }
        public decimal net2 { get; set; }
        public decimal tan_net { get; set; }
        public string cancel_type { get; set; }
        public string acccate { get; set; }
        public decimal par_value_deal_ntd { get; set; }
        /// <summary>
        /// 現存面額
        /// </summary>
        public decimal par_value_ntd { get; set; }
        public decimal bef_int_ntd { get; set; }
        /// <summary>
        /// 現存成本
        /// </summary>
        public decimal net_ntd { get; set; }
        public decimal before_tax_ntd { get; set; }
        public decimal net2_deal_ntd { get; set; }
        public decimal net2_ntd { get; set; }
        public decimal tan_net_ntd { get; set; }
    }
}