// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bdrs_account
    {
        public string broker_code { get; set; }
        public string account_code { get; set; }
        public string account_name { get; set; }
        public string account_section { get; set; }
    }
}