// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bdrs_trans_new
    {
        public string fund_no { get; set; }
        public DateTime? tran_date { get; set; }
        public string deal_no { get; set; }
        public string new_deal_no { get; set; }
    }
}