// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bdrs_fundacct
    {
        /// <summary>
        /// 基金代號
        /// </summary>
        public string fund_no { get; set; }
        /// <summary>
        /// 帳號
        /// </summary>
        public string account_code { get; set; }
        /// <summary>
        /// 戶名
        /// </summary>
        public string account_name { get; set; }
    }
}