// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bdrs_inventory
    {
        public string fund_no { get; set; }
        /// <summary>
        /// 債券編號
        /// </summary>
        public string bond_no { get; set; }
        /// <summary>
        /// 庫存面額(現庫存中的總面額)
        /// </summary>
        public decimal par_value { get; set; }
        /// <summary>
        /// 允許承作面額 (可以質借的上限)
        /// </summary>
        public decimal limit_value { get; set; }
        /// <summary>
        /// 己質借面額
        /// </summary>
        public decimal pawned_value { get; set; }
        public decimal? spare_value { get; set; }
        /// <summary>
        /// 使用者代號  
        /// </summary>
        public string user_id { get; set; }
        /// <summary>
        /// 最後修改時間(年月日時分秒)
        /// </summary>
        public DateTime last_update { get; set; }
    }
}