// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bdrs_inventory_log
    {
        public string fund_no { get; set; }
        public string bond_no { get; set; }
        public decimal par_value { get; set; }
        public decimal limit_value { get; set; }
        public decimal pawned_value { get; set; }
        public decimal? spare_value { get; set; }
        public string user_id { get; set; }
        public DateTime last_update { get; set; }
    }
}