// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class bdrs_trans_ref
    {
        /// <summary>
        /// 狀態
        /// </summary>
        public byte rec_status { get; set; }
        /// <summary>
        /// 基金代號
        /// </summary>
        public string fund_no { get; set; }
        /// <summary>
        /// 債券代號
        /// </summary>
        public string bond_no { get; set; }
        /// <summary>
        /// 交易編號
        /// </summary>
        public string deal_no { get; set; }
        public string new_deal_no_01 { get; set; }
        public string new_deal_no_02 { get; set; }
        public byte? tran_levels { get; set; }
        /// <summary>
        /// 交易對手(券商)
        /// </summary>
        public string broker_code { get; set; }
        /// <summary>
        /// 交易日期
        /// </summary>
        public DateTime tran_date { get; set; }
        /// <summary>
        /// 交易金額
        /// </summary>
        public decimal tran_price { get; set; }
        /// <summary>
        /// 債券面額
        /// </summary>
        public decimal bond_value { get; set; }
        /// <summary>
        /// 承作利率(預計)
        /// </summary>
        public decimal tran_rate { get; set; }
        /// <summary>
        /// 承作天數(預計)
        /// </summary>
        public int tran_days { get; set; }
        /// <summary>
        /// 到期日期(預計)
        /// </summary>
        public DateTime end_date { get; set; }
        /// <summary>
        /// 利息費用(預計)
        /// </summary>
        public decimal int_fee { get; set; }
        /// <summary>
        /// 到期償還金額(預計)
        /// </summary>
        public decimal? pay_price { get; set; }
    }
}