// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class Book1
    {
        public string tran_date { get; set; }
        public string pool_no { get; set; }
        public string sub_poo { get; set; }
        public string fund_code { get; set; }
        public string volumn { get; set; }
        public string avg_cost { get; set; }
        public string local_cost { get; set; }
        public string cost_rate { get; set; }
        public string base_cost { get; set; }
        public string market_price { get; set; }
        public string local_market_value { get; set; }
        public string local_price_benefit { get; set; }
        public string ex_rate { get; set; }
        public string base_market_value { get; set; }
        public string baes_price_benefit { get; set; }
        public string base_exrate_benefit { get; set; }
    }
}