// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class ca_brokerpay
    {
        public string sys_no { get; set; }
        public string fund_no { get; set; }
        public DateTime tran_date { get; set; }
        public string broker_code { get; set; }
        public string pay_type { get; set; }
        public decimal pay_net { get; set; }
        public string pay_title { get; set; }
        public string pay_account { get; set; }
        /// <summary>
        /// 應收金額
        /// </summary>
        public decimal? sold_amt { get; set; }
        /// <summary>
        /// 應付金額
        /// </summary>
        public decimal? buy_amt { get; set; }
        /// <summary>
        /// RP(1-淨額法,2-總額法)SB(1-買賣斷非TB,2-非買賣斷TB,3-非買賣斷非TB)
        /// </summary>
        public string acct_type { get; set; }
    }
}