// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class ca_cat008_log
    {
        public decimal recno { get; set; }
        public DateTime tran_date { get; set; }
        public string bank_acct { get; set; }
        public string check_no { get; set; }
        public decimal amt { get; set; }
        public string title_old { get; set; }
        public string change_memo_old { get; set; }
        public string title_new { get; set; }
        public string change_memo_new { get; set; }
        public string op { get; set; }
        public decimal status { get; set; }
    }
}