// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class ca_car051_memo
    {
        public string memo_dept { get; set; }
        public DateTime tran_date { get; set; }
        public int memo_no { get; set; }
        public string memo_name { get; set; }
        public decimal memo_amt { get; set; }
    }
}