// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class ca_cashitem
    {
        public string item_code { get; set; }
        public string description { get; set; }
        public string description1 { get; set; }
        public string drcr { get; set; }
        public string sys_no { get; set; }
    }
}