// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class ca_cat079_log
    {
        public string vounoA { get; set; }
        public int rownumA { get; set; }
        public DateTime tran_date { get; set; }
        public string bank_acct { get; set; }
        public string dr_cr { get; set; }
        public decimal amt { get; set; }
        public string type { get; set; }
        public string cash_item { get; set; }
        public string memo { get; set; }
        public string ccy_type { get; set; }
    }
}