// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class ca_cat018_log
    {
        public DateTime tran_date { get; set; }
        public decimal seq_no { get; set; }
        public decimal recno { get; set; }
        public string cash_item_old { get; set; }
        public string cash_item_new { get; set; }
        public string ins_op_old { get; set; }
        public string ins_op_new { get; set; }
    }
}