// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class ca_check_gl_dtl
    {
        public decimal recno { get; set; }
        public decimal seq_no { get; set; }
        public DateTime tran_date { get; set; }
        public string bank_acct { get; set; }
        public string gl { get; set; }
        public decimal amt { get; set; }
        public decimal batch_no { get; set; }
        public decimal acc { get; set; }
        public string memo { get; set; }
        public string r_code { get; set; }
        public string gl_memo { get; set; }
    }
}