// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class ca_group_exp_amt
    {
        public DateTime tran_date { get; set; }
        public string group_no { get; set; }
        public decimal exp_amt { get; set; }
    }
}