// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class ca_item_base
    {
        public string item_no { get; set; }
        public string item_name { get; set; }
        public string group_no { get; set; }
        public string group_no_car052 { get; set; }
        public int ntd { get; set; }
        public int fc { get; set; }
        public string dr_cr { get; set; }
    }
}