// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class ca_remit_info
    {
        public string source { get; set; }
        public string broker_co { get; set; }
        public string broker_code { get; set; }
        public string remit_bank { get; set; }
        public string remit_branch { get; set; }
        public string remit_account { get; set; }
    }
}