// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class ca_restdate
    {
        public int month { get; set; }
        public DateTime restdate { get; set; }
        public string accounting { get; set; }
    }
}