// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class ca_source_item_mapping
    {
        public int source_type { get; set; }
        public string source_code { get; set; }
        public string item_no_in { get; set; }
        public string item_no_out { get; set; }
    }
}