// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class ca_unlock_log
    {
        public string id_no { get; set; }
        public DateTime? unlock_date { get; set; }
        public string unlock_reason { get; set; }
        public DateTime? login_date { get; set; }
        public string login_time { get; set; }
    }
}