// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class car009memo
    {
        public DateTime tran_date { get; set; }
        public decimal a1 { get; set; }
        public decimal a2 { get; set; }
        public decimal a3 { get; set; }
        public decimal a4 { get; set; }
        public decimal a5 { get; set; }
        public decimal a6 { get; set; }
        public decimal a7 { get; set; }
        public decimal b1 { get; set; }
        public decimal c1 { get; set; }
        public decimal d1 { get; set; }
        public decimal e1 { get; set; }
        public decimal e2 { get; set; }
        public decimal e3 { get; set; }
        public decimal e4 { get; set; }
        public decimal e5 { get; set; }
        public decimal e6 { get; set; }
        public decimal e7 { get; set; }
        public decimal e8 { get; set; }
        public decimal f1 { get; set; }
        public decimal f2 { get; set; }
        public decimal f3 { get; set; }
        public decimal f4 { get; set; }
        public decimal f5 { get; set; }
        public decimal f6 { get; set; }
        public decimal f7 { get; set; }
        public decimal g1 { get; set; }
        public decimal g2 { get; set; }
        public decimal g3 { get; set; }
        public decimal g4 { get; set; }
        public decimal g5 { get; set; }
        public decimal g6 { get; set; }
        public decimal h1 { get; set; }
        public decimal h2 { get; set; }
        public decimal h3 { get; set; }
        public decimal h4 { get; set; }
        public decimal h5 { get; set; }
        public decimal h6 { get; set; }
        public decimal i1 { get; set; }
        public decimal i2 { get; set; }
        public decimal i3 { get; set; }
        public decimal i4 { get; set; }
    }
}