// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class cash_status
    {
        public DateTime sys_date { get; set; }
        public bool status1 { get; set; }
        public bool status2 { get; set; }
    }
}