// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class cash_item_mapping
    {
        public string old_no { get; set; }
        public string new_no { get; set; }
    }
}