// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class cash_plan
    {
        public DateTime tran_date { get; set; }
        public decimal sb_amt { get; set; }
        public decimal td_amt { get; set; }
        public decimal bf_amt { get; set; }
        public decimal rs_amt { get; set; }
        public decimal hold_amt { get; set; }
        public decimal bank_amt { get; set; }
        public string hold_desc { get; set; }
        public decimal share_amt { get; set; }
    }
}