// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class CAT080_Acct
    {
        public int seq_no { get; set; }
        public DateTime tran_date { get; set; }
        public string bank_acct { get; set; }
        public decimal amt_i { get; set; }
        public decimal amt_o { get; set; }
        public string memo { get; set; }
        public int is_check { get; set; }
        public DateTime check_date { get; set; }
        public int acct_recno { get; set; }
    }
}