// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class CAT080_Bank
    {
        public int seq_no { get; set; }
        public string bank_acct { get; set; }
        public string tran_date_long { get; set; }
        public string agent { get; set; }
        public string brief_memo { get; set; }
        public decimal amt_i { get; set; }
        public decimal amt_o { get; set; }
        public decimal dendbal { get; set; }
        public string memo { get; set; }
        public string deal_info { get; set; }
        public int is_check { get; set; }
        public DateTime tran_date { get; set; }
        public DateTime check_date { get; set; }
    }
}