// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class ccy_base
    {
        public string ccy { get; set; }
        public string ccy_name { get; set; }
        public string ccy_e_name { get; set; }
        public decimal? int_base_days { get; set; }
        public decimal? fraction_num { get; set; }
        public decimal? cash_fraction_num { get; set; }
        public decimal? swap_fraction_num { get; set; }
        public string country_code { get; set; }
    }
}