// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class ccy_rate_list
    {
        public DateTime tran_date { get; set; }
        public string ccy_type1 { get; set; }
        public string ccy_type2 { get; set; }
        public decimal ccy_rate { get; set; }
        public decimal td_amt { get; set; }
    }
}