// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class check_add
    {
        public string bank_acct { get; set; }
        public string beg_chk_no { get; set; }
        public string end_chk_no { get; set; }
        public int cnt { get; set; }
        public DateTime add_date { get; set; }
        public string user_id { get; set; }
    }
}