// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class check_tmp_1
    {
        public DateTime? check_date { get; set; }
        public string check_no { get; set; }
        public double? amt { get; set; }
        public string seqid { get; set; }
    }
}