// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class Check_detail_yes
    {
        public string change_date { get; set; }
        public string pay_memo { get; set; }
        public string title { get; set; }
        public string bank_acct { get; set; }
        public string check_no { get; set; }
        public string acct_date { get; set; }
        public string amt { get; set; }
        public string dept_no { get; set; }
    }
}