// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class chgtypetest
    {
        public string fund_no { get; set; }
        public DateTime change_date { get; set; }
        public string change_type { get; set; }
        public string sk_code_old { get; set; }
        public string sk_code_new { get; set; }
        public decimal volumn_old01 { get; set; }
        public decimal volumn_old02 { get; set; }
        public decimal net { get; set; }
        public decimal volumn_new01 { get; set; }
        public decimal volumn_new02 { get; set; }
        public string sk_type_old { get; set; }
        public string sk_type_new { get; set; }
    }
}