// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class code_file
    {
        /// <summary>
        /// 代號類別
        /// </summary>
        public string item_type { get; set; }
        /// <summary>
        /// 代號編號
        /// </summary>
        public string item_code { get; set; }
        /// <summary>
        /// 代號中文說明
        /// </summary>
        public string description { get; set; }
        /// <summary>
        /// 代號描述
        /// </summary>
        public string remark { get; set; }
    }
}