// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class cs_trans
    {
        public DateTime tran_date { get; set; }
        public string tran_no { get; set; }
        public string fund_no { get; set; }
        public string bank_code { get; set; }
        public string bank_account { get; set; }
        public string action { get; set; }
        public string good_no { get; set; }
        public string ccy { get; set; }
        public decimal amt { get; set; }
        public decimal? exrate { get; set; }
        public decimal? nt_amt { get; set; }
        public string remark { get; set; }
        public DateTime? settle_date { get; set; }
        public string rec_status { get; set; }
        public string op_bank { get; set; }
        public string op_account { get; set; }
    }
}