// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class cs_total_hist
    {
        /// <summary>
        /// 交易日期
        /// </summary>
        public DateTime tran_date { get; set; }
        /// <summary>
        /// 券商總公司代號 (sb_broker.broker_co)
        /// </summary>
        public string bank_code { get; set; }
        public string bank_account { get; set; }
        /// <summary>
        /// 金額
        /// </summary>
        public decimal amt { get; set; }
        /// <summary>
        /// 台幣金額
        /// </summary>
        public decimal nt_amt { get; set; }
    }
}