// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class da_acct_dtl
    {
        public decimal recno { get; set; }
        public DateTime tran_date { get; set; }
        public string contract_no { get; set; }
        public string dr_cr { get; set; }
        public decimal amt { get; set; }
        public string cash_item { get; set; }
    }
}