// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class da_bank_endbal_hist
    {
        public string contract_no { get; set; }
        public decimal dendbal { get; set; }
        public decimal dr_amt { get; set; }
        public decimal cr_amt { get; set; }
        public DateTime tran_date { get; set; }
    }
}