// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class da_contract_base
    {
        public string contract_no { get; set; }
        public string contract_name { get; set; }
        public DateTime beg_date { get; set; }
        public DateTime end_date { get; set; }
        public decimal contract_amt { get; set; }
        public string bank_acct { get; set; }
        public string bank_no { get; set; }
        public string branch_no { get; set; }
        public string co_name { get; set; }
    }
}