// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class dafn_divid
    {
        /// <summary>
        /// 帳冊別
        /// </summary>
        public string fund_no { get; set; }
        /// <summary>
        /// 投信公司代號
        /// </summary>
        public string fn_co { get; set; }
        /// <summary>
        /// 基金代號
        /// </summary>
        public string fn_no { get; set; }
        /// <summary>
        /// 除息日期
        /// </summary>
        public DateTime ex_date { get; set; }
        /// <summary>
        /// 當日持有數
        /// </summary>
        public decimal hold_share { get; set; }
        /// <summary>
        /// 除息率
        /// </summary>
        public decimal div_rate { get; set; }
        /// <summary>
        /// 配息金額(除息金額)
        /// </summary>
        public decimal total_amt { get; set; }
        /// <summary>
        /// 所得稅率
        /// </summary>
        public float? tax_rate { get; set; }
        /// <summary>
        /// 所得稅額
        /// </summary>
        public decimal? tax_amt { get; set; }
        /// <summary>
        /// 應收淨額(除息淨額)
        /// </summary>
        public decimal? net_amt { get; set; }
        /// <summary>
        /// 領息日
        /// </summary>
        public DateTime? recv_date { get; set; }
        /// <summary>
        /// 交易別
        /// </summary>
        public string action { get; set; }
        /// <summary>
        /// 實際領取總數
        /// </summary>
        public decimal? rec_amt { get; set; }
        /// <summary>
        /// 銀行代號
        /// </summary>
        public string bank_code { get; set; }
        /// <summary>
        /// 銀行帳號
        /// </summary>
        public string bank_account { get; set; }
        /// <summary>
        /// 郵費匯費
        /// </summary>
        public decimal? fee_amt { get; set; }
        /// <summary>
        /// 溢配金額
        /// </summary>
        public decimal? over_dividend { get; set; }
        /// <summary>
        /// 會計分類
        /// </summary>
        public string acccate { get; set; }
        public string p_code { get; set; }
    }
}