// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class dafn_trans
    {
        /// <summary>
        /// 交易別(1-買 2-賣)
        /// </summary>
        public string action { get; set; }
        /// <summary>
        /// 交易編號
        /// </summary>
        public string deal_no { get; set; }
        /// <summary>
        /// 帳冊別
        /// </summary>
        public string fund_no { get; set; }
        /// <summary>
        /// 投信公司代號
        /// </summary>
        public string fn_co { get; set; }
        /// <summary>
        /// 投信合約代碼
        /// </summary>
        public string contract_code { get; set; }
        /// <summary>
        /// 基金代號
        /// </summary>
        public string fn_no { get; set; }
        /// <summary>
        /// 券商代號
        /// </summary>
        public string broker_code { get; set; }
        /// <summary>
        /// 會計分類
        /// </summary>
        public string acccate { get; set; }
        /// <summary>
        /// 成交日期
        /// </summary>
        public DateTime tran_date { get; set; }
        /// <summary>
        /// 成交金額
        /// </summary>
        public decimal tot_amt { get; set; }
        /// <summary>
        /// 成交數量
        /// </summary>
        public decimal tot_unit { get; set; }
        /// <summary>
        /// 成交單價
        /// </summary>
        public decimal unit_nav { get; set; }
        /// <summary>
        /// 手續費
        /// </summary>
        public decimal broker_fee { get; set; }
        /// <summary>
        /// 匯費
        /// </summary>
        public decimal bank_fee { get; set; }
        /// <summary>
        /// 交易稅
        /// </summary>
        public decimal trans_tax { get; set; }
        /// <summary>
        /// 淨額
        /// </summary>
        public decimal net { get; set; }
        /// <summary>
        /// 成本
        /// </summary>
        public decimal fund_cost { get; set; }
        /// <summary>
        /// 交割狀態
        /// </summary>
        public short dtl_status { get; set; }
        /// <summary>
        /// 投信的交易編號
        /// </summary>
        public string memo { get; set; }
        /// <summary>
        /// 下單日
        /// </summary>
        public DateTime? trade_date { get; set; }
        /// <summary>
        /// 交割日期
        /// </summary>
        public DateTime? settle_date { get; set; }
        /// <summary>
        /// 券交割日
        /// </summary>
        public DateTime? settledate_bill { get; set; }
        public string p_code { get; set; }
    }
}