// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class dask_divid
    {
        /// <summary>
        /// 帳戶別
        /// </summary>
        public string fund_no { get; set; }
        /// <summary>
        /// 投信公司代號
        /// </summary>
        public string fn_co { get; set; }
        /// <summary>
        /// 股票代號
        /// </summary>
        public string sk_code { get; set; }
        public string acccate { get; set; }
        /// <summary>
        /// 交易別(1.除息2.盈配3.公配4.現增)
        /// </summary>
        public string action { get; set; }
        /// <summary>
        /// 除權除息日期
        /// </summary>
        public DateTime ex_date { get; set; }
        /// <summary>
        /// 當日持有股數
        /// </summary>
        public decimal hold_share { get; set; }
        /// <summary>
        /// 配股息比率(除權除息率)
        /// </summary>
        public decimal div_rate { get; set; }
        /// <summary>
        /// 配股股數(除權股數)
        /// </summary>
        public decimal? total_share { get; set; }
        /// <summary>
        /// 原始配息金額(投信不含盈餘、公積)
        /// </summary>
        public decimal? org_total_amt { get; set; }
        /// <summary>
        /// 配息金額(除息金額)
        /// </summary>
        public decimal total_amt { get; set; }
        /// <summary>
        /// 所得稅率
        /// </summary>
        public float tax_rate { get; set; }
        /// <summary>
        /// 所得稅額
        /// </summary>
        public decimal tax_amt { get; set; }
        /// <summary>
        /// 領股領息日
        /// </summary>
        public DateTime? recv_date { get; set; }
        /// <summary>
        /// 郵費匯費
        /// </summary>
        public decimal? fee_amt { get; set; }
        /// <summary>
        /// 除權實領股數
        /// </summary>
        public decimal? rec_amt { get; set; }
        /// <summary>
        /// 除權溢配金額
        /// </summary>
        public decimal? over_dividend { get; set; }
        /// <summary>
        /// 除息實領金額
        /// </summary>
        public decimal net_amt { get; set; }
        /// <summary>
        /// 除息實領淨額
        /// </summary>
        public decimal? pre_total_amt { get; set; }
        /// <summary>
        /// 除息溢配金額
        /// </summary>
        public decimal? over_int { get; set; }
        /// <summary>
        /// 銀行代號
        /// </summary>
        public string bank_code { get; set; }
        /// <summary>
        /// 銀行帳號
        /// </summary>
        public string bank_account { get; set; }
    }
}