// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class dask_taxfree
    {
        /// <summary>
        /// 投信公司代號
        /// </summary>
        public string fn_co { get; set; }
        /// <summary>
        /// 交易日
        /// </summary>
        public DateTime tran_date { get; set; }
        /// <summary>
        /// 股票代號
        /// </summary>
        public string sk_code { get; set; }
        /// <summary>
        /// 除權日
        /// </summary>
        public DateTime? d_date { get; set; }
        /// <summary>
        /// 盈配金額
        /// </summary>
        public decimal s_amt { get; set; }
        /// <summary>
        /// 盈配可扣底比率
        /// </summary>
        public decimal s_percent { get; set; }
        /// <summary>
        /// 盈配可扣底稅額
        /// </summary>
        public decimal stock_taxfree { get; set; }
        /// <summary>
        /// 公配金額
        /// </summary>
        public decimal f_amt { get; set; }
        /// <summary>
        /// 公配可扣底比率
        /// </summary>
        public decimal f_percent { get; set; }
        /// <summary>
        /// 公配可扣底稅額
        /// </summary>
        public decimal fund_taxfree { get; set; }
        /// <summary>
        /// 除息日
        /// </summary>
        public DateTime? c_date { get; set; }
        /// <summary>
        /// 除息金額
        /// </summary>
        public decimal c_amt { get; set; }
        /// <summary>
        /// 除息可扣抵比率
        /// </summary>
        public decimal c_percent { get; set; }
        /// <summary>
        /// 除息可扣抵金額
        /// </summary>
        public decimal cash_taxfree { get; set; }
        public string action { get; set; }
        public decimal? benfit_86 { get; set; }
        public decimal? benfit_87 { get; set; }
        public decimal surplus_amt { get; set; }
        public decimal surplus_percent { get; set; }
        public decimal surplus_taxfree { get; set; }
        /// <summary>
        /// 持有股數類別
        /// </summary>
        public string sys_type { get; set; }
    }
}