// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class dept_base
    {
        public string dept_no { get; set; }
        public string dept_name { get; set; }
        public decimal rpt_amt { get; set; }
    }
}