// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class dm_tra_fo_deal
    {
        public string trade_no { get; set; }
        public string brk_tran_no { get; set; }
        public int pno { get; set; }
        public string fno { get; set; }
        public DateTime trade_dt { get; set; }
        public string code { get; set; }
        public string cont_no { get; set; }
        public DateTime exp_dt { get; set; }
        public short cap_tp { get; set; }
        public string broker { get; set; }
        public short trade_tp { get; set; }
        public short bs_tp { get; set; }
        public short cp_tp { get; set; }
        public decimal lot { get; set; }
        public decimal amt { get; set; }
        public decimal pre_amt { get; set; }
        public decimal price { get; set; }
        public decimal tran_fee { get; set; }
        public decimal tran_tax { get; set; }
        public decimal other_fee { get; set; }
        public string comb_no { get; set; }
        public decimal cost_diff { get; set; }
        public DateTime org_trade_dt { get; set; }
        public string org_trade_no { get; set; }
        public decimal org_price { get; set; }
        public decimal org_pre_amt { get; set; }
        public string manager { get; set; }
        public string approve { get; set; }
        public string trader { get; set; }
        public DateTime approve_dt { get; set; }
        public string etl_trade_tp { get; set; }
        public string etl_trade_no { get; set; }
        public short data_tp { get; set; }
        public string crtuser { get; set; }
        public DateTime crttime { get; set; }
        public bool _lock { get; set; }
        public string lockuser { get; set; }
        public DateTime locktime { get; set; }
        public string loguser { get; set; }
        public DateTime logtime { get; set; }
    }
}