// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class dm_tra_td_pledge_chg
    {
        public string buy_trade_no { get; set; }
        public DateTime chg_dt { get; set; }
        public short is_pledge_bf { get; set; }
        public short is_pledge { get; set; }
        public short data_tp { get; set; }
        public bool _lock { get; set; }
        public string lockuser { get; set; }
        public DateTime locktime { get; set; }
        public string loguser { get; set; }
        public DateTime logtime { get; set; }
    }
}