// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class emp_base
    {
        /// <summary>
        /// 使用者登入帳號
        /// </summary>
        public string sales_id { get; set; }
        /// <summary>
        /// 使用者統一編號
        /// </summary>
        public string emp_id { get; set; }
        /// <summary>
        /// 使用者中文姓名
        /// </summary>
        public string emp_name { get; set; }
        /// <summary>
        /// 密碼
        /// </summary>
        public string passwd { get; set; }
        /// <summary>
        /// 離職(否)
        /// </summary>
        public bool dimission { get; set; }
        /// <summary>
        /// 登入失敗次數
        /// </summary>
        public short fail_cnt { get; set; }
        /// <summary>
        /// 擁有所有基金權限
        /// </summary>
        public bool manage { get; set; }
        public string dept_name { get; set; }
        public string role_no { get; set; }
    }
}