// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fas_no_tmp
    {
        public string deal_no { get; set; }
        public string fas_deal_no { get; set; }
    }
}