// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fc_exchange_tran
    {
        public DateTime tran_date { get; set; }
        public string acct_out { get; set; }
        public string ccy_out { get; set; }
        public decimal out_amt { get; set; }
        public string acct_in { get; set; }
        public string ccy_in { get; set; }
        public decimal ccy_rate { get; set; }
        public decimal in_amt { get; set; }
        public decimal nt_rate { get; set; }
        public decimal nt_amt { get; set; }
        public string type { get; set; }
    }
}