// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fn_alarm
    {
        public string fn_no { get; set; }
        public DateTime tran_date { get; set; }
        public string action { get; set; }
    }
}