// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fn_Announce
    {
        /// <summary>
        /// 基金公司
        /// </summary>
        public string fn_co { get; set; }
        /// <summary>
        /// 基金代號
        /// </summary>
        public string fn_no { get; set; }
        /// <summary>
        /// 公告日
        /// </summary>
        public DateTime AnnounceDate { get; set; }
        /// <summary>
        /// 交易起
        /// </summary>
        public DateTime BegDate { get; set; }
        /// <summary>
        /// 交易止
        /// </summary>
        public DateTime EndDate { get; set; }
        /// <summary>
        /// 交易單位淨值(非收盤)
        /// </summary>
        public decimal BegDateUnitNav { get; set; }
        /// <summary>
        /// 交易單位淨值(非收盤)
        /// </summary>
        public decimal EndDateUnitNav { get; set; }
        /// <summary>
        /// 平均單位淨值(非收盤)
        /// </summary>
        public decimal AvgUnitNav { get; set; }
        /// <summary>
        /// 交易單位數
        /// </summary>
        public decimal TradeUnit { get; set; }
        public decimal TradeAvgUnitNav { get; set; }
        /// <summary>
        /// 交易總金額
        /// </summary>
        public decimal TradeAmt { get; set; }
        /// <summary>
        /// 己實現損益
        /// </summary>
        public decimal GainLoss { get; set; }
        /// <summary>
        /// 庫存單位(含公告日)
        /// </summary>
        public decimal StockUnit { get; set; }
        /// <summary>
        /// 庫存金額(含公告日)
        /// </summary>
        public decimal StockAmt { get; set; }
        /// <summary>
        /// 持有比率StockUnit/Fn_TotUnits
        /// </summary>
        public decimal HoldRate { get; set; }
        /// <summary>
        /// 買/賣
        /// </summary>
        public string BS { get; set; }
        /// <summary>
        /// 基金發行總單位數
        /// </summary>
        public decimal Fn_TotUnits { get; set; }
    }
}