// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fn_bk_hold_hist_tmp
    {
        public string fn_no { get; set; }
        public string broker_code { get; set; }
        public decimal tot_units { get; set; }
        public decimal chg_units { get; set; }
        public DateTime tran_date { get; set; }
    }
}