// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fn_base
    {
        public int? fn_base_Seq { get; set; }
        public string fn_co { get; set; }
        public string fn_no { get; set; }
        public string fn_name { get; set; }
        public string fn_s_name { get; set; }
        public string englishname { get; set; }
        public string estimate { get; set; }
        public string estimate_co { get; set; }
        public string fn_type { get; set; }
        public string acccate { get; set; }
        public short nav_round { get; set; }
        public short unit_round { get; set; }
        public string bank_no { get; set; }
        public string branch_no { get; set; }
        public string fn_bank_title { get; set; }
        public string fn_bank_acct { get; set; }
        public string pay_type { get; set; }
        public string fn_excelname { get; set; }
        public int? settle_day { get; set; }
        public string data_source { get; set; }
        public string fn_type_dtl { get; set; }
        public string CMoneyID { get; set; }
        public short? cdtp { get; set; }
    }
}