// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fn_bd_data
    {
        public string ibdid { get; set; }
        public string fdis { get; set; }
        public string sedol { get; set; }
        public string isin { get; set; }
        public string cusip { get; set; }
        public string bbgcode { get; set; }
        public string ID_TAIWAN { get; set; }
        public string ID_SHORT_CODE { get; set; }
        public string JPSecurityID { get; set; }
        public string nbd { get; set; }
        public string ncbd { get; set; }
        public string ftype { get; set; }
        public string subtype { get; set; }
        public string Degree { get; set; }
        public string COUNTRY { get; set; }
        public string CNTRY_OF_RISK { get; set; }
        public string issuerid { get; set; }
        public string issuerName { get; set; }
        public string GuaranteeID { get; set; }
        public string GuaranteeName { get; set; }
        public string icurid { get; set; }
        public string OTC { get; set; }
        public string SENIOR { get; set; }
        public bool? IS_SECURED { get; set; }
        public bool? Private { get; set; }
        public decimal? issue_amt { get; set; }
        public decimal? prate { get; set; }
        public string dissuer { get; set; }
        public DateTime? dissuer_w { get; set; }
        public string dend { get; set; }
        public DateTime? dend_w { get; set; }
        public string EXCH_CODE { get; set; }
        public DateTime? pdate { get; set; }
        public int? PriceUnit { get; set; }
        public string Cpn_Typ { get; set; }
        public string Day_Cnt_Des { get; set; }
        public string CntType { get; set; }
        public int? CntMonth { get; set; }
        public string IOPO { get; set; }
        public int? Mtg_Pay_Delay { get; set; }
        public int? Portia_Mtg_Pay_Delay { get; set; }
        public string yday { get; set; }
        public string mday { get; set; }
        public int? Cpn_Freq { get; set; }
        public int? rcount { get; set; }
        public string DateType { get; set; }
        public int? PaymentDays { get; set; }
        public string StaticPayDate { get; set; }
        public int? qdmon { get; set; }
        public int? PaymentMonth { get; set; }
        public int? qfmon { get; set; }
        public decimal? taxrate { get; set; }
        public decimal? AMT_OUTSTANDING { get; set; }
        public decimal? StableRate { get; set; }
        public string SecClass { get; set; }
        public string SecurityType { get; set; }
        public string CashBalance { get; set; }
        public string Market_Sector_Des { get; set; }
        public string Industry_Sector { get; set; }
        public string Industry_SubGroup { get; set; }
        public string SevenRegions { get; set; }
        public string EightArea { get; set; }
        public string TransactionType { get; set; }
        public string AssetType { get; set; }
        public string Floatation { get; set; }
        public string PaymentStatus { get; set; }
        public DateTime? dLastPurchase { get; set; }
        public int? freqPurchase { get; set; }
        public bool? Rule12th { get; set; }
        public bool? IsPerpetualBond { get; set; }
        public bool? IsZeroBond { get; set; }
        public DateTime? First_Cpn_Dt { get; set; }
        public bool? IsEnable { get; set; }
        public DateTime time_update { get; set; }
        public string CIType { get; set; }
        public int? issuerSeq { get; set; }
        public int? GuaranteeSeq { get; set; }
        public string issuer_IndustrySectorType { get; set; }
        public string issuer_ServiceST { get; set; }
        public string Guarantee_ServiceST { get; set; }
        public bool? issuer_IsStockPrice { get; set; }
        public string TAS_bond_kind { get; set; }
        public string TAS_Glbond_kind { get; set; }
        public string TAS_fx_type { get; set; }
        public string ExposureCountryType { get; set; }
        public string ExposureCountryName { get; set; }
        public string ExposureCountryCode { get; set; }
        public string PayStatus { get; set; }
        public string ChangeReq { get; set; }
        public bool? IsSPPI { get; set; }
        public DateTime? NXT_CALL_DT { get; set; }
        public decimal? MTG_ORIG_AMT { get; set; }
        public DateTime? Blg_time_update { get; set; }
        public DateTime? TAS_time_update { get; set; }
    }
}