// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fn_co
    {
        public int? fn_co_UID { get; set; }
        public string fn_co1 { get; set; }
        public string co_name { get; set; }
        public string co_s_name { get; set; }
        public string englishname { get; set; }
        public string signature { get; set; }
        public int relationship { get; set; }
        public string unityid { get; set; }
        /// <summary>
        /// 是否為委外系統投信公司
        /// </summary>
        public int da_type { get; set; }
        public string relation_no { get; set; }
        public string CMoneyID { get; set; }
        public string Ticker { get; set; }
    }
}