// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fn_compare_list
    {
        public string fund_no { get; set; }
        public string fn_no { get; set; }
        public DateTime tran_date { get; set; }
        public string corp_name { get; set; }
        public string fn_name { get; set; }
        public decimal? unit_nav { get; set; }
        public decimal? profitability { get; set; }
        public short? rank { get; set; }
        public decimal? nav_week { get; set; }
        public decimal? aweek { get; set; }
        public short? rank_week { get; set; }
        public decimal? nav_month { get; set; }
        public decimal? amonth { get; set; }
        public short? rank_month { get; set; }
        public decimal? nav_quarter { get; set; }
        public decimal? aquarter { get; set; }
        public short? rank_quarter { get; set; }
        public decimal? nav_semi { get; set; }
        public decimal? semi_annual { get; set; }
        public short? rank_semi_annual { get; set; }
        public decimal? scale { get; set; }
    }
}