// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fn_dividinfo
    {
        public string fn_no { get; set; }
        public DateTime? c_date { get; set; }
        public decimal cash_dividend { get; set; }
        public int rec_no { get; set; }
        public bool? rec_status { get; set; }
        public DateTime? meeting_date { get; set; }
        public DateTime? c_recv_date { get; set; }
        public DateTime? ins_date { get; set; }
        public string ins_op { get; set; }
    }
}