// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fn_dealer_etf
    {
        public string fund_no { get; set; }
        public string broker_code { get; set; }
    }
}