// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fn_inout_dtl
    {
        public DateTime tran_date { get; set; }
        public string broker_in { get; set; }
        public string broker_out { get; set; }
        public string fn_no { get; set; }
        public decimal tot_units { get; set; }
        public decimal seq_no { get; set; }
    }
}