// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fn_ImportLog
    {
        public string CompuerName { get; set; }
        public string user_name { get; set; }
        public DateTime? tran_date { get; set; }
        public DateTime crtdate { get; set; }
    }
}