// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fn_invest_list
    {
        public string fund_no { get; set; }
        public string fn_no { get; set; }
        public DateTime tran_date { get; set; }
        public short serial_no { get; set; }
        public string col1 { get; set; }
        public string col2 { get; set; }
        public decimal? col3 { get; set; }
    }
}