// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fn_Issuer_rating
    {
        /// <summary>
        /// &apos;資料日期&apos;
        /// </summary>
        public DateTime? ddate { get; set; }
        public string RateCo { get; set; }
        /// <summary>
        /// &apos;機構Ticker&apos;
        /// </summary>
        public string IssuerID { get; set; }
        public DateTime? LastUpdate { get; set; }
        /// <summary>
        /// &apos;S&amp;P長期外幣發行人信用評等&apos;
        /// </summary>
        public string RTG_SP_LT_FC_ISSUER_CREDIT { get; set; }
        /// <summary>
        /// &apos;S&amp;P本國貨幣長期發行人信用評等&apos;
        /// </summary>
        public string RTG_SP_LT_LC_ISSUER_CREDIT { get; set; }
        /// <summary>
        /// &apos;MOODY發行人信評&apos;
        /// </summary>
        public string RTG_MDY_ISSUER { get; set; }
        /// <summary>
        /// &apos;MOODY長期評等&apos;
        /// </summary>
        public string RTG_MOODY_LONG_TERM { get; set; }
        /// <summary>
        /// &apos;MOODY外幣發行人評等&apos;
        /// </summary>
        public string RTG_MDY_FC_CURR_ISSUER_RATING { get; set; }
        /// <summary>
        /// &apos;MOODY優先無擔保債務評等&apos;
        /// </summary>
        public string RTG_MDY_SEN_UNSECURED_DEBT { get; set; }
        /// <summary>
        /// &apos;FITCH長期發行人違約評等&apos;
        /// </summary>
        public string RTG_FITCH_LT_ISSUER_DEFAULT { get; set; }
        /// <summary>
        /// &apos;FITCH長期外幣發行人違約評等&apos;
        /// </summary>
        public string RTG_FITCH_LT_FC_ISSUER_DEFAULT { get; set; }
        /// <summary>
        /// &apos;中華信評&apos;
        /// </summary>
        public string RTG_TRC_LONG_TERM { get; set; }
        /// <summary>
        /// &apos;台灣惠譽信評&apos;
        /// </summary>
        public string RTG_FITCH_NATIONAL_LT { get; set; }
        public string op { get; set; }
    }
}