// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fn_ipo_advance
    {
        public string ipo_deal_no { get; set; }
        public string fund_no { get; set; }
        public string fn_co { get; set; }
        public string fn_no { get; set; }
        public DateTime trade_date { get; set; }
        public decimal redemption_unit { get; set; }
        public string broker_code { get; set; }
        public string ipo_chk { get; set; }
        public DateTime? settle_date { get; set; }
        public DateTime? settledate_bill { get; set; }
        public string is_use { get; set; }
    }
}