// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class Fn_PaperData
    {
        public DateTime PaperDate { get; set; }
        public decimal AssertRate { get; set; }
        public decimal StockHolder { get; set; }
        public decimal WorkingMoney { get; set; }
    }
}