// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fn_plan
    {
        public string fund_no { get; set; }
        public string fn_no { get; set; }
        public short action { get; set; }
        public DateTime tran_date { get; set; }
        public DateTime pay_date { get; set; }
        public decimal tot_unit { get; set; }
        public decimal unit_nav { get; set; }
        public decimal tot_amt { get; set; }
    }
}