// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fn_report
    {
        public DateTime tran_date { get; set; }
        public string action { get; set; }
        public string fn_no { get; set; }
        public string fn_name { get; set; }
        public string fn_co { get; set; }
        public string co_name { get; set; }
        public decimal tot_unit { get; set; }
        public decimal unit_nav { get; set; }
        public decimal tot_amt { get; set; }
        public decimal tot_units { get; set; }
    }
}