// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fn_swap
    {
        public string fund_no { get; set; }
        public string fn_no { get; set; }
        public DateTime? swap_date { get; set; }
        public decimal? trust_swap_unit { get; set; }
        public decimal? confirm_swap_unit { get; set; }
        public decimal? trust_unit { get; set; }
        public decimal? confirm_unit { get; set; }
        public short? dtl_status { get; set; }
    }
}