// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fn_total_d
    {
        public string fund_no { get; set; }
        public string d_code { get; set; }
        public string fn_co { get; set; }
        public string fn_no { get; set; }
        public string acccate { get; set; }
        public decimal tot_units { get; set; }
        public decimal net { get; set; }
        public decimal avg_cost { get; set; }
        public decimal unit_nav { get; set; }
        public decimal market_price { get; set; }
        public decimal year_gain { get; set; }
        public decimal year_loss { get; set; }
        public decimal month_gain { get; set; }
        public decimal month_loss { get; set; }
        public decimal day_gain { get; set; }
        public decimal day_loss { get; set; }
        public decimal chg_units { get; set; }
        public decimal chg_cost { get; set; }
        public DateTime tran_date { get; set; }
        public decimal confirm_unit { get; set; }
        public decimal trust_unit { get; set; }
        public decimal year_dividend { get; set; }
        public decimal month_dividend { get; set; }
        public decimal day_dividend { get; set; }
    }
}