// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fn_taxfree
    {
        public DateTime tran_date { get; set; }
        public string fund_no { get; set; }
        public string fn_no { get; set; }
        public DateTime? c_date { get; set; }
        public decimal c_amt { get; set; }
        public decimal c_percent { get; set; }
        public decimal cash_taxfree { get; set; }
        public string action { get; set; }
        public decimal? benfit_86 { get; set; }
        public decimal? benfit_87 { get; set; }
    }
}