// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class ft_account_list
    {
        public string broker_no { get; set; }
        public string account { get; set; }
        public string account_name { get; set; }
        public string bank_name { get; set; }
        public string fund_no { get; set; }
        public string account_purpose { get; set; }
        public string out_account { get; set; }
    }
}