// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class ft_broker
    {
        public string broker_no { get; set; }
        public string broker_name { get; set; }
        public string unityid { get; set; }
        public decimal? fee { get; set; }
        public decimal? feeo { get; set; }
    }
}