// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class ft_base
    {
        /// <summary>
        /// 商品代號
        /// </summary>
        public string ft_no { get; set; }
        /// <summary>
        /// 商品名稱
        /// </summary>
        public string ft_name { get; set; }
        public string fo_type { get; set; }
        public string ft_type { get; set; }
        /// <summary>
        /// 單價
        /// </summary>
        public decimal point_price { get; set; }
        /// <summary>
        /// 原始保證金
        /// </summary>
        public decimal ini_ins { get; set; }
        /// <summary>
        /// 維持保證金
        /// </summary>
        public decimal mt_ins { get; set; }
        public string ft_no2 { get; set; }
        public decimal? tax { get; set; }
        public string evaluation_level { get; set; }
    }
}