// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class ft_daily_margin
    {
        public string broker_no { get; set; }
        public string account { get; set; }
        public decimal ini_margin { get; set; }
        public decimal mt_margin { get; set; }
        public DateTime tran_date { get; set; }
    }
}