// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class ft_margin_tran
    {
        public string broker_no { get; set; }
        public string account { get; set; }
        public DateTime tran_date { get; set; }
        public string action { get; set; }
        public decimal amount { get; set; }
        public decimal? tax { get; set; }
        public string tran_no { get; set; }
    }
}