// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class ft_price
    {
        public DateTime tran_date { get; set; }
        public string ft_no { get; set; }
        public string ft_ym { get; set; }
        public string cp_type { get; set; }
        public decimal ex_value { get; set; }
        public decimal price { get; set; }
    }
}