// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class ftp_upload_log
    {
        public DateTime op_time { get; set; }
        public string op_user { get; set; }
        public string user_prog { get; set; }
        public DateTime? rpt_end_date { get; set; }
        public string mono { get; set; }
    }
}