// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fund_price
    {
        public string fund_code { get; set; }
        public decimal price { get; set; }
        public DateTime tran_date { get; set; }
        public decimal seq_no { get; set; }
    }
}