// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fund_charge
    {
        public string fund_no { get; set; }
        public DateTime tran_date { get; set; }
        public decimal? fund_unit { get; set; }
        public decimal? bond_unit { get; set; }
        public string fund_no_a { get; set; }
        public string bond_no_a { get; set; }
        public decimal? fund_price { get; set; }
        public decimal? bond_price { get; set; }
    }
}