// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fx_account
    {
        public double? F1 { get; set; }
        public string acccount { get; set; }
        public string Classification { get; set; }
        public string Name { get; set; }
        public string Non_USD__Account_NO_ { get; set; }
        public string Trustee__Bank { get; set; }
        public string 會計科子_目編號 { get; set; }
        /// <summary>
        /// 會計科目
        /// </summary>
        public string acc_title { get; set; }
        /// <summary>
        /// 會計子目
        /// </summary>
        public string acc_subtitle { get; set; }
        public double? 簽收 { get; set; }
    }
}