// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fx_account_execute
    {
        public string account { get; set; }
        public string emp { get; set; }
        public string check_no { get; set; }
    }
}