// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fx_account_file
    {
        /// <summary>
        /// 帳戶
        /// </summary>
        public string account { get; set; }
        /// <summary>
        /// 帳戶別
        /// </summary>
        public string fund_no { get; set; }
        /// <summary>
        /// 帳戶名稱
        /// </summary>
        public string fund_name { get; set; }
        /// <summary>
        /// 帳戶英文名
        /// </summary>
        public string fund_ename { get; set; }
        /// <summary>
        /// 專案或信托
        /// </summary>
        public string attitude { get; set; }
        /// <summary>
        /// 會計分類
        /// </summary>
        public string acccate { get; set; }
        /// <summary>
        /// 券種種類
        /// </summary>
        public string fx_type { get; set; }
        /// <summary>
        /// 債券種類
        /// </summary>
        public string bond_kind { get; set; }
        /// <summary>
        /// 帳戶順序
        /// </summary>
        public int? account_seq { get; set; }
        public string ccy_type_base { get; set; }
        public int? roundnum { get; set; }
        public string derivatives { get; set; }
        public string chk_china { get; set; }
        public string chk_taiwan { get; set; }
        public string fx_bank { get; set; }
    }
}