// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fx_bank_acc
    {
        public string bank_no { get; set; }
        public int state { get; set; }
        /// <summary>
        /// 種類  對到fx_found_file.attitude (03: 信托    02:專案)
        /// </summary>
        public string type { get; set; }
        /// <summary>
        /// 銀行簡稱
        /// </summary>
        public string bank_alias { get; set; }
        /// <summary>
        /// account no
        /// </summary>
        public string acno { get; set; }
        /// <summary>
        /// 戶名
        /// </summary>
        public string acc_name { get; set; }
        /// <summary>
        /// 解款行
        /// </summary>
        public string paying_bank { get; set; }
    }
}