// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fx_category
    {
        public int number { get; set; }
        public string security_type { get; set; }
        public string gl_type { get; set; }
        public string fx_type { get; set; }
        public string bond_kind { get; set; }
    }
}