// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fx_chg_security_id
    {
        public string account { get; set; }
        public DateTime chg_date { get; set; }
        public string security_id_old { get; set; }
        public string security_id { get; set; }
        public string currency_code { get; set; }
    }
}