// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fx_diff_temp
    {
        public int serial { get; set; }
        public string account { get; set; }
        public DateTime? trade_date { get; set; }
        public DateTime? last_date { get; set; }
        public string curr_code { get; set; }
        public decimal? net_amount { get; set; }
        public string emp { get; set; }
    }
}