// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fx_ExchRate
    {
        /// <summary>
        /// 銀行代碼
        /// </summary>
        public string BrokerCode { get; set; }
        public DateTime TradeDate { get; set; }
    }
}