// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fx_fund_file
    {
        /// <summary>
        /// 基金代號(fund_file.fund_no)
        /// </summary>
        public string fund_no { get; set; }
        /// <summary>
        /// 基金公會代號
        /// </summary>
        public string fund_id { get; set; }
        /// <summary>
        /// 基金名稱
        /// </summary>
        public string fund_name { get; set; }
        /// <summary>
        /// 基金屬性(code_file.item_type = ‘F1’)
        /// </summary>
        public string attitude { get; set; }
        public string inv_area { get; set; }
        /// <summary>
        /// 經理費率
        /// </summary>
        public decimal? manage_fee { get; set; }
        /// <summary>
        /// 保管費率
        /// </summary>
        public decimal? fee { get; set; }
        /// <summary>
        /// 活存息計息方式(code_file.item_type =’B3’)
        /// </summary>
        public string int_type { get; set; }
        /// <summary>
        /// 管理費計費方式(code_file.item_type = ‘B2’)
        /// </summary>
        public string fee_type { get; set; }
        /// <summary>
        /// 保管費計費起日
        /// </summary>
        public DateTime? fee_date { get; set; }
        /// <summary>
        /// 經理費計費起日
        /// </summary>
        public DateTime? managefee_date { get; set; }
        /// <summary>
        /// 每月最低經理費
        /// </summary>
        public decimal? min_manage_fee { get; set; }
        /// <summary>
        /// 每月最低保管費
        /// </summary>
        public decimal? min_fee { get; set; }
        /// <summary>
        /// 基金經理人代號(emp_base.sales_id)
        /// </summary>
        public string manage_op { get; set; }
        /// <summary>
        /// 會計人員代號(emp_base.sales_id)
        /// </summary>
        public string acc_op { get; set; }
        /// <summary>
        /// 股票交易員代號(emp_base.sales_id)
        /// </summary>
        public string sk_op { get; set; }
        /// <summary>
        /// 資金調度員代號(emp_base.sales_id)
        /// </summary>
        public string sb_op { get; set; }
        /// <summary>
        /// 業務人員代號(emp_base.sales_id)
        /// </summary>
        public string sales_op { get; set; }
        /// <summary>
        /// 活存利率
        /// </summary>
        public decimal? bank_rate { get; set; }
        /// <summary>
        /// 保管銀行代號(sb_broker.broker_co)
        /// </summary>
        public string bank_no { get; set; }
        /// <summary>
        /// 分行代號(sb_broker.broker_code)
        /// </summary>
        public string branch_no { get; set; }
        /// <summary>
        /// 保管銀行帳號
        /// </summary>
        public string bank_acct { get; set; }
        /// <summary>
        /// 開帳日期
        /// </summary>
        public DateTime? start_date { get; set; }
        /// <summary>
        /// 成立日期
        /// </summary>
        public DateTime? beg_date { get; set; }
        /// <summary>
        /// 終止日期
        /// </summary>
        public DateTime? end_date { get; set; }
        /// <summary>
        /// 基金鎖定(否)
        /// </summary>
        public string _lock { get; set; }
        /// <summary>
        /// 單位數小數點位數
        /// </summary>
        public int? unit_round { get; set; }
        /// <summary>
        /// 單位淨值小數點位數
        /// </summary>
        public int? nav_round { get; set; }
        /// <summary>
        /// 開帳淨資產價值
        /// </summary>
        public decimal? nav { get; set; }
        /// <summary>
        /// 開帳單位數
        /// </summary>
        public decimal? units { get; set; }
        /// <summary>
        /// 基金統編
        /// </summary>
        public string ban { get; set; }
        /// <summary>
        /// 保管費半年付費日
        /// </summary>
        public short? fee_day { get; set; }
        /// <summary>
        /// 保管費半年付費日
        /// </summary>
        public short? int_day { get; set; }
        /// <summary>
        /// 最低持股比率
        /// </summary>
        public decimal? stock_rate { get; set; }
        /// <summary>
        /// 未達持股費用折扣率
        /// </summary>
        public decimal? fee_rate { get; set; }
        /// <summary>
        /// 身分別
        /// </summary>
        public string p_type { get; set; }
        /// <summary>
        /// 生日/成立日
        /// </summary>
        public DateTime? birth_date { get; set; }
        /// <summary>
        /// 負責人
        /// </summary>
        public string charge_man { get; set; }
        /// <summary>
        /// 電話一
        /// </summary>
        public string tel_no_1 { get; set; }
        /// <summary>
        /// 電話二
        /// </summary>
        public string tel_no_2 { get; set; }
        /// <summary>
        /// 傳真
        /// </summary>
        public string fax_no { get; set; }
        /// <summary>
        /// 郵遞區號一(code_file.item_type = ‘Z1’)
        /// </summary>
        public string zip_code_1 { get; set; }
        /// <summary>
        /// 聯絡地址一
        /// </summary>
        public string addr1 { get; set; }
        /// <summary>
        /// 郵遞區號二
        /// </summary>
        public string zip_code_2 { get; set; }
        /// <summary>
        /// 聯絡地址二
        /// </summary>
        public string addr2 { get; set; }
        /// <summary>
        /// 建檔日期
        /// </summary>
        public DateTime? ins_date { get; set; }
        public string run_type { get; set; }
        public string trust_bank { get; set; }
        public string trust_branch { get; set; }
        public string trust_acct { get; set; }
        /// <summary>
        /// 基金名稱
        /// </summary>
        public string fund_ename { get; set; }
        public string acccate { get; set; }
        public string fx_type { get; set; }
        public string bond_kind { get; set; }
        /// <summary>
        /// 系統目前作帳時程
        /// </summary>
        public string sys_char { get; set; }
        /// <summary>
        /// 系統上一營業日
        /// </summary>
        public DateTime? last_date { get; set; }
        /// <summary>
        /// 系統目前作帳日期
        /// </summary>
        public DateTime? sys_date { get; set; }
        /// <summary>
        /// 系統下一營業日
        /// </summary>
        public DateTime? next_date { get; set; }
        /// <summary>
        /// 系統下二營業日
        /// </summary>
        public DateTime? af_next_date { get; set; }
    }
}