// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fx_file
    {
        /// <summary>
        /// 交易日期
        /// </summary>
        public DateTime tran_date { get; set; }
        /// <summary>
        /// 現在交易幣別
        /// </summary>
        public string curr_code { get; set; }
        public decimal us_rate { get; set; }
        /// <summary>
        /// 台幣買入匯率
        /// </summary>
        public decimal nt_rate { get; set; }
    }
}