// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fx_gl_setup
    {
        public string sys_no { get; set; }
        public string fund_no { get; set; }
        public string action { get; set; }
        public string account { get; set; }
        public string acccate { get; set; }
        public string 類別 { get; set; }
        public string gl { get; set; }
        public string sl1 { get; set; }
        public string gdesc { get; set; }
        public string drcr { get; set; }
        public string memo { get; set; }
        public int serial { get; set; }
        public string type { get; set; }
        public string attitude { get; set; }
        public decimal? serial2 { get; set; }
        public string bond_kind { get; set; }
    }
}