// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fx_hist
    {
        public string tran_no { get; set; }
        public string fund_no { get; set; }
        public DateTime? tran_date { get; set; }
        public string account { get; set; }
        public DateTime? trade_date { get; set; }
        public DateTime? settlement_date { get; set; }
        public DateTime? effective_date { get; set; }
        public string secu_desc1 { get; set; }
        public string secu_desc2 { get; set; }
        public string security_id { get; set; }
        public string curr_code { get; set; }
        public decimal? net_amount { get; set; }
        public decimal? ex_rate { get; set; }
        public decimal? shares_units { get; set; }
        public decimal? net_amount_base { get; set; }
        public string summary_type { get; set; }
        public string detail_type { get; set; }
        public decimal? net_amount_nt { get; set; }
        public decimal? buy_int { get; set; }
        public decimal? buy_int_nt { get; set; }
        public decimal? proc_fee { get; set; }
        public decimal? proc_fee_nt { get; set; }
        public string action { get; set; }
        public decimal? buy_cost_nt { get; set; }
        public decimal? buy_unit_price { get; set; }
        public decimal? net_amount_sett { get; set; }
        public decimal? net_amount_sett_nt { get; set; }
        public string ref_account { get; set; }
    }
}