// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fx_ImportLog
    {
        public string CompuerName { get; set; }
        public string action { get; set; }
        public DateTime crtdate { get; set; }
    }
}