// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fx_market_fair
    {
        public DateTime? tran_date { get; set; }
        public string acccate_item { get; set; }
        public string security_id { get; set; }
        public decimal? shares_units_total { get; set; }
        public decimal? fund_cost_ntd_total { get; set; }
        public decimal? market_ntd { get; set; }
        public decimal? gain_loss { get; set; }
        public string fair_level { get; set; }
        public string account { get; set; }
        public string chk { get; set; }
    }
}