// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fx_mapping_tmp
    {
        public string ISIN { get; set; }
        public string CITI_SID { get; set; }
        public string JP_SID { get; set; }
    }
}