// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fx_overdue_income
    {
        public DateTime? tran_date { get; set; }
        public string account_number { get; set; }
        public string security_id { get; set; }
        public decimal? overdue_income_local { get; set; }
        public decimal? overdue_income_base { get; set; }
    }
}