// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fx_security
    {
        public decimal serial { get; set; }
        /// <summary>
        /// 基金代號(fund_file.fund_no)
        /// </summary>
        public string fund_no { get; set; }
        /// <summary>
        /// 交易日期
        /// </summary>
        public DateTime? tran_date { get; set; }
        public string base_currency_code { get; set; }
        public string account_number { get; set; }
        public string account_name { get; set; }
        public string security_description1 { get; set; }
        public string security_description2 { get; set; }
        public decimal? cupon { get; set; }
        public DateTime? maturity { get; set; }
        public string security_id { get; set; }
        public string isin { get; set; }
        public string segment { get; set; }
        public string category { get; set; }
        public string sector { get; set; }
        public string industry { get; set; }
        public decimal? shares_units { get; set; }
        public decimal? price { get; set; }
        public string currency_code { get; set; }
        public string country { get; set; }
        public decimal? cost_value_local { get; set; }
        /// <summary>
        /// 原幣市場價值(原幣)
        /// </summary>
        public decimal as_of_market_value_local { get; set; }
        /// <summary>
        /// 實際所得net(原幣)
        /// </summary>
        public decimal? net_accrued_income_local { get; set; }
        /// <summary>
        /// 未實現的損益(原幣)
        /// </summary>
        public decimal? unrealized_gain_loss_local { get; set; }
        /// <summary>
        /// 成本價值(美金)
        /// </summary>
        public decimal? cost_value_base { get; set; }
        /// <summary>
        /// 市場價值
        /// </summary>
        public decimal? as_of_market_value_base { get; set; }
        /// <summary>
        /// 實際所得淨額(美金)
        /// </summary>
        public decimal? net_accrued_income_base { get; set; }
        /// <summary>
        /// 未實現的損益(美金)
        /// </summary>
        public decimal? unrealized_gain_loss_base { get; set; }
        /// <summary>
        /// 未實現的損益百分比(美金)
        /// </summary>
        public decimal? percent_of_unrealized_gain_loss_base { get; set; }
        public decimal? percent_of_total_portfolio { get; set; }
        public string security_type { get; set; }
    }
}