// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fx_security_hist
    {
        public string fund_no { get; set; }
        public DateTime? tran_date { get; set; }
        public string base_currency_code { get; set; }
        public string account_number { get; set; }
        public string account_name { get; set; }
        public string security_description1 { get; set; }
        public string security_description2 { get; set; }
        public decimal? cupon { get; set; }
        public DateTime? maturity { get; set; }
        public string security_id { get; set; }
        public string isin { get; set; }
        public string segment { get; set; }
        public string category { get; set; }
        public string sector { get; set; }
        public string industry { get; set; }
        public decimal? shares_units { get; set; }
        public decimal? price { get; set; }
        public string currency_code { get; set; }
        public string country { get; set; }
        public decimal? cost_value_local { get; set; }
        public decimal as_of_market_value_local { get; set; }
        public decimal? net_accrued_income_local { get; set; }
        public decimal? unrealized_gain_loss_local { get; set; }
        public decimal? cost_value_base { get; set; }
        public decimal? as_of_market_value_base { get; set; }
        public decimal? net_accrued_income_base { get; set; }
        public decimal? unrealized_gain_loss_base { get; set; }
        public decimal? percent_of_unrealized_gain_loss_base { get; set; }
        public decimal? percent_of_total_portfolio { get; set; }
        public string security_type { get; set; }
    }
}