// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fx_total_delete
    {
        public string fund_no { get; set; }
        public DateTime tran_date { get; set; }
        public string base_curr_code { get; set; }
        public string account { get; set; }
        public string secu_desc1 { get; set; }
        public string secu_desc2 { get; set; }
        public string security_id { get; set; }
        public string segment { get; set; }
        public string category { get; set; }
        public string sector { get; set; }
        public string industry { get; set; }
        public decimal? shares_units { get; set; }
        public decimal? price { get; set; }
        public string currency_code { get; set; }
        public string country { get; set; }
        public decimal? cost_value { get; set; }
        public decimal? market_value { get; set; }
        public decimal? net_accrued_income { get; set; }
        public decimal? unrealized_gain_loss { get; set; }
        public decimal? cost_value_base { get; set; }
        public decimal? market_value_base { get; set; }
        public decimal? net_accrued_income_base { get; set; }
        public decimal? unrealized_gain_loss_base { get; set; }
        public decimal? percent_of_unrealized_gain_loss_base { get; set; }
        public decimal? percent_of_total_portfolio { get; set; }
        public decimal? buy_local_cost { get; set; }
        public decimal? buy_nt_cost { get; set; }
        public decimal? sale_units { get; set; }
        public decimal? sale_local_cost { get; set; }
        public decimal? sale_nt_cost { get; set; }
        public decimal? sale_net_Amount { get; set; }
        public decimal? sale_net_Amount_nt { get; set; }
        public decimal? sale_net_Amount_profit { get; set; }
        public decimal? sale_net_Amount_nt_profit { get; set; }
        public decimal? sale_exchange_profit { get; set; }
        public decimal? month_amortisation_amt { get; set; }
        public decimal? month_amortisation_bf_cost { get; set; }
        public decimal? eval_bef_cost_nt { get; set; }
        public decimal? eval_af_cost_nt { get; set; }
        public decimal? eval_af_market_value_nt { get; set; }
        public decimal? eval_af_exchange_profit { get; set; }
        public decimal? price_diff_profile { get; set; }
        public DateTime? action_date { get; set; }
        public string net_accrued_income_curr_code { get; set; }
        public decimal? market_value_cost { get; set; }
        public decimal serial { get; set; }
    }
}