// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fx_Trade_Receivables_Payables_hist
    {
        public int item_serial { get; set; }
        public DateTime tran_date { get; set; }
        public string account_number { get; set; }
        public string trade_currency { get; set; }
        public DateTime trade_date { get; set; }
        public DateTime settlement_date { get; set; }
        public string security_description { get; set; }
        public string security_id { get; set; }
        public string transaction_type { get; set; }
        public decimal quantity { get; set; }
        public decimal principal_local { get; set; }
        public decimal income_local { get; set; }
        public string security_type { get; set; }
    }
}