// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class fx_transaction_delete
    {
        public string tran_no { get; set; }
        public string fund_no { get; set; }
        public DateTime? tran_date { get; set; }
        public string account_number { get; set; }
        public string account_name { get; set; }
        public DateTime? trade_date { get; set; }
        public DateTime? settlement_date { get; set; }
        public DateTime? effective_date { get; set; }
        public string security_description1 { get; set; }
        public string security_description2 { get; set; }
        public string security_id { get; set; }
        public string currency_code { get; set; }
        public decimal? net_amount_local { get; set; }
        public decimal? exchange_rate { get; set; }
        public decimal? shares_units { get; set; }
        public decimal? net_amount_base { get; set; }
        public string summary_transaction_type { get; set; }
        public string detail_transaction_type { get; set; }
        public string transaction_description1 { get; set; }
        public string transaction_description2 { get; set; }
        public string action { get; set; }
        public string ref_account { get; set; }
    }
}