// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class ics_cash_upload
    {
        public string TRAN_SERIAL_SEQ { get; set; }
        public int TRAN_BATCH_SEQ { get; set; }
        public DateTime? CV_DATE { get; set; }
        public string VERSION { get; set; }
        public string TRAN_DATA_ID { get; set; }
        public string ASSETS_CODE_DTL { get; set; }
        public DateTime? STOCK_DATE { get; set; }
        public string SUB_COMPANY_CODE { get; set; }
        public string AC_CURRENCY { get; set; }
        public string P_ACCOUNT { get; set; }
        public DateTime? EXP_DATE { get; set; }
        public string DEPO_ACCOUNT { get; set; }
        public string CURRENCY { get; set; }
        public decimal? AMOUNT { get; set; }
        public string LOGUSER { get; set; }
        public DateTime? LOGTIME { get; set; }
    }
}