// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class il_action_info
    {
        public string action { get; set; }
        public string action_c { get; set; }
        public int tas_action { get; set; }
        public int deal_way { get; set; }
    }
}