// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class il_fund_price
    {
        public DateTime tran_date { get; set; }
        public string fund_code { get; set; }
        public decimal fund_price { get; set; }
        public string input_way { get; set; }
    }
}