// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class il_fund_co
    {
        public string fund_co { get; set; }
        public string fund_co_alias { get; set; }
        public string fund_co_name { get; set; }
    }
}