// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class il_fund_mng_rate
    {
        public string mng_bank { get; set; }
        public string fund_code { get; set; }
        public DateTime tran_date { get; set; }
        public decimal mng_rate { get; set; }
    }
}