// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class il_fund_base
    {
        public string fund_code { get; set; }
        public string fund_alias { get; set; }
        public string fund_name { get; set; }
        public string ccy_type { get; set; }
        public string fund_type { get; set; }
        public string fund_sub_type { get; set; }
        public string fund_co { get; set; }
        public string o_code { get; set; }
    }
}