// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class il_fund_total_vlife
    {
        public DateTime tran_date { get; set; }
        public string pool_no { get; set; }
        public string il_code { get; set; }
        public string fund_code { get; set; }
        public decimal volumn { get; set; }
        public decimal avg_cost { get; set; }
        public decimal local_cost { get; set; }
        public decimal cost_rate { get; set; }
        public decimal base_cost { get; set; }
        public decimal market_price { get; set; }
        public decimal local_market_value { get; set; }
        public decimal local_price_benefit { get; set; }
        public decimal ex_rate { get; set; }
        public decimal base_market_value { get; set; }
        public decimal base_price_benefit { get; set; }
        public decimal base_exrate_benefit { get; set; }
    }
}