// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class il_fund_total_tmp
    {
        public decimal tran_no { get; set; }
        public string tran_date { get; set; }
        public string deal_date { get; set; }
        public string il_code { get; set; }
        public string pool_no { get; set; }
        public string sub_pool { get; set; }
        public string action { get; set; }
        public string fund_code { get; set; }
        public decimal volumn { get; set; }
        public decimal avg_cost { get; set; }
        public decimal local_cost { get; set; }
        public decimal cost_rate { get; set; }
        public decimal base_cost { get; set; }
        public decimal local_cost1 { get; set; }
        public decimal base_cost1 { get; set; }
        public int price_benefit { get; set; }
        public int exrate_benefit { get; set; }
        public string source_type { get; set; }
        public string settle_date { get; set; }
        public string key_way { get; set; }
    }
}