// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class il_fund_trans
    {
        public string tran_no { get; set; }
        public DateTime? deal_date { get; set; }
        public DateTime tran_date { get; set; }
        public string il_code { get; set; }
        public string pool_no { get; set; }
        public string sub_pool { get; set; }
        public string action { get; set; }
        public string fund_code { get; set; }
        public decimal volumn { get; set; }
        public decimal unit_price { get; set; }
        public decimal local_amt { get; set; }
        public decimal ex_rate { get; set; }
        public decimal base_amt { get; set; }
        public decimal local_cost { get; set; }
        public decimal base_cost { get; set; }
        public decimal price_benefit { get; set; }
        public decimal exrate_benefit { get; set; }
        public string source_type { get; set; }
        public DateTime? settle_date { get; set; }
        public string input_way { get; set; }
    }
}