// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class il_pool_map
    {
        public string il_code { get; set; }
        public string il_name { get; set; }
        public string fund_code { get; set; }
        public string pool_no { get; set; }
    }
}