// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class il_pool_base
    {
        public string pool_no { get; set; }
        public string pool_name { get; set; }
        public string ccy_type { get; set; }
        public string ex_type { get; set; }
        public DateTime? sys_date { get; set; }
        public int pool_order { get; set; }
        public string mng_bank { get; set; }
        public string pool_type { get; set; }
        public int oiu { get; set; }
        public string _class { get; set; }
        public string bank_code { get; set; }
    }
}