// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class inv_bnd_bal
    {
        public DateTime date { get; set; }
        public string code { get; set; }
        public int pno { get; set; }
        public string fno { get; set; }
        public string cap_tp { get; set; }
        public string trade_no { get; set; }
        public decimal org_par_value { get; set; }
        public decimal settle_org_par_value { get; set; }
        public decimal qty { get; set; }
        public decimal acc_qty { get; set; }
        public decimal settle_qty { get; set; }
        public decimal acc_settle_qty { get; set; }
        public decimal unlist_buy { get; set; }
        public decimal unlist_sell { get; set; }
        public decimal unlist_xchg { get; set; }
        public decimal cust_qty { get; set; }
        public decimal cost { get; set; }
        public decimal acc_cost { get; set; }
        public decimal settle_cost { get; set; }
        public decimal acc_settle_cost { get; set; }
        public decimal _int { get; set; }
        public decimal acc_int { get; set; }
        public decimal eom_int { get; set; }
        public decimal acc_eom_int { get; set; }
        public decimal bef_int { get; set; }
        public decimal acc_bef_int { get; set; }
        public decimal bef_int_tax { get; set; }
        public decimal acc_bef_int_tax { get; set; }
        public decimal amortize { get; set; }
        public decimal acc_amortize { get; set; }
        public decimal eom_amortize { get; set; }
        public decimal acc_eom_amortize { get; set; }
        public decimal buy_premdisc { get; set; }
        public decimal acc_buy_premdisc { get; set; }
        public decimal sale_premdisc { get; set; }
        public decimal acc_sale_premdisc { get; set; }
        public decimal sale_buy { get; set; }
        public decimal acc_sale_buy { get; set; }
        public decimal sale_amor { get; set; }
        public decimal acc_sale_amor { get; set; }
        public decimal write_down { get; set; }
        public decimal acc_write_down { get; set; }
        public decimal acc_write_down_exch { get; set; }
        public decimal factor { get; set; }
        public decimal amt { get; set; }
        public decimal acc_amt { get; set; }
        public decimal price { get; set; }
        public decimal exchrate { get; set; }
        public decimal duration { get; set; }
        public decimal yield { get; set; }
        public decimal cost_diff { get; set; }
        public decimal acc_cost_diff { get; set; }
        public decimal acc_exch_diff { get; set; }
        public decimal eom_cost_diff { get; set; }
        public decimal acc_eom_cost_diff { get; set; }
        public decimal acc_eom_exch_diff { get; set; }
        public decimal acc_eom_int_exch { get; set; }
        public decimal opt_diff { get; set; }
        public decimal acc_opt_diff { get; set; }
        public decimal tax_diff { get; set; }
        public decimal acc_tax_diff { get; set; }
        public decimal acc_tax_exch_diff { get; set; }
        public decimal rl_cost_diff { get; set; }
        public decimal acc_rl_cost_diff { get; set; }
        public decimal acc_rl_exch_diff { get; set; }
        public decimal rl_int_diff { get; set; }
        public decimal acc_rl_int_diff { get; set; }
        public decimal acc_rl_int_exch { get; set; }
        public decimal rl_tax_prepaid { get; set; }
        public decimal acc_rl_tax_prepaid { get; set; }
        public decimal res_int { get; set; }
        public string loguser { get; set; }
        public DateTime logtime { get; set; }
    }
}