// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class level_change
    {
        public DateTime change_date { get; set; }
        public string sys_no { get; set; }
        public string goods_code { get; set; }
        public string price_level { get; set; }
    }
}