// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class lk_bank
    {
        public string bank_code { get; set; }
        public string bank_no { get; set; }
        public string address { get; set; }
        public string account { get; set; }
        public string tel { get; set; }
        public string broker_code { get; set; }
        public string contact { get; set; }
    }
}