// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class lk_chang
    {
        public string fund_no { get; set; }
        public string tran_no { get; set; }
        public DateTime tran_date { get; set; }
        public DateTime? old_enddate { get; set; }
        public DateTime? new_enddate { get; set; }
    }
}