// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class lk_hist
    {
        public string rec_status { get; set; }
        public string fund_no { get; set; }
        public string tran_no { get; set; }
        public string rec_tranno { get; set; }
        public string broker_code { get; set; }
        public string action_type { get; set; }
        public string sk_code { get; set; }
        public decimal volumn { get; set; }
        public DateTime beg_date { get; set; }
        public DateTime end_date { get; set; }
        public decimal rate { get; set; }
        public string acccate { get; set; }
        public decimal avg_cost { get; set; }
        public decimal fund_cost { get; set; }
        public string action { get; set; }
        public DateTime tran_date { get; set; }
        public string bank_code { get; set; }
        public decimal? interest { get; set; }
        public decimal? cover { get; set; }
        public decimal? poundage { get; set; }
        public decimal? tax { get; set; }
    }
}