// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class lk_trans_divid_count
    {
        public string fund_no { get; set; }
        public DateTime tran_date { get; set; }
        public string tran_no { get; set; }
        public string action_lk_trans { get; set; }
        public string sk_code { get; set; }
        public string acccate { get; set; }
        public string broker_code { get; set; }
        public DateTime ex_date_divid { get; set; }
        public string action_divid { get; set; }
        public decimal hold_share { get; set; }
        public decimal? total_share { get; set; }
        public decimal? total_amt { get; set; }
        public decimal? net_amt { get; set; }
        public string p_code { get; set; }
    }
}