// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class lk_total_chg
    {
        public string fund_no { get; set; }
        public string tran_no { get; set; }
        public DateTime tran_date { get; set; }
        public string sk_code { get; set; }
        public decimal volumn { get; set; }
        public string p_code { get; set; }
        public string org_p_code { get; set; }
    }
}