// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class lk_total
    {
        public string rec_status { get; set; }
        /// <summary>
        /// 基金代號
        /// </summary>
        public string fund_no { get; set; }
        /// <summary>
        /// 交易編號
        /// </summary>
        public string tran_no { get; set; }
        /// <summary>
        /// 券商編號
        /// </summary>
        public string broker_code { get; set; }
        public string action_type { get; set; }
        /// <summary>
        /// 股票代號
        /// </summary>
        public string sk_code { get; set; }
        public decimal volumn { get; set; }
        public DateTime beg_date { get; set; }
        public DateTime end_date { get; set; }
        public decimal rate { get; set; }
        public string acccate { get; set; }
        public decimal avg_cost { get; set; }
        public decimal fund_cost { get; set; }
        public DateTime tran_date { get; set; }
        /// <summary>
        /// 利息收入
        /// </summary>
        public decimal? interest { get; set; }
        public string bank_code { get; set; }
        /// <summary>
        /// 服務費
        /// </summary>
        public decimal? cover { get; set; }
        /// <summary>
        /// 手續費
        /// </summary>
        public decimal? poundage { get; set; }
        public decimal? total_int { get; set; }
        public DateTime? last_begdate { get; set; }
        public string p_code { get; set; }
    }
}