// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class no34_chgtype
    {
        public string sys_no { get; set; }
        public string fund_no { get; set; }
        public string prod_no { get; set; }
        public string deal_no { get; set; }
        public DateTime tran_date { get; set; }
        public string _long { get; set; }
        public string category { get; set; }
        public decimal lcm_amt { get; set; }
        public decimal? tran_parvalue { get; set; }
        public decimal? tran_net { get; set; }
        public string exp_category { get; set; }
    }
}