// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class no34_chg_record
    {
        public string sys_no { get; set; }
        public string fund_no { get; set; }
        public string prod_no { get; set; }
        public string term { get; set; }
        public string old_acccate { get; set; }
        public decimal old_units { get; set; }
        public decimal old_cost { get; set; }
        public string new_acccate { get; set; }
        public decimal new_units { get; set; }
        public decimal new_cost { get; set; }
        public DateTime tran_date { get; set; }
        public decimal lcm_amt { get; set; }
        public decimal confirm_unit { get; set; }
        public decimal trust_unit { get; set; }
    }
}