// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class odbc_info
    {
        public int seq_no { get; set; }
        public string sql_source { get; set; }
        public string sql_name { get; set; }
        public string sql_passwd { get; set; }
        public string sql_desc { get; set; }
    }
}