// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class op_change
    {
        public string action { get; set; }
        public decimal action_type { get; set; }
        public string fund_no { get; set; }
        public string broker_code { get; set; }
        public DateTime tran_date { get; set; }
        public string bond_kind { get; set; }
        public string bond_no { get; set; }
        public decimal par_value { get; set; }
        public decimal? sheet { get; set; }
        public string save_model { get; set; }
        public string save_type { get; set; }
        public string broker_code2 { get; set; }
        public decimal? amount { get; set; }
        public string tran_no { get; set; }
        public string app_no { get; set; }
        public string save_model1 { get; set; }
        public string save_type1 { get; set; }
        public string dvp_fop { get; set; }
        public string chk_print { get; set; }
    }
}