// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class op_dtl
    {
        public string fund_no { get; set; }
        public string app_no { get; set; }
        public string bill_no { get; set; }
        public string bill_type { get; set; }
        public DateTime bill_begdate { get; set; }
        public DateTime bill_enddate { get; set; }
        public string unified_no { get; set; }
        public string bill_name { get; set; }
        public string insure_name { get; set; }
        public decimal par_value { get; set; }
        public decimal bill_rate { get; set; }
        public decimal bill_int { get; set; }
        public int bill_days { get; set; }
        public string relation { get; set; }
    }
}