// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class op_inv_hist
    {
        public string fund_no { get; set; }
        public DateTime tran_date { get; set; }
        public string bond_kind { get; set; }
        public string bond_no { get; set; }
        public string save_model { get; set; }
        public string save_type { get; set; }
        public string broker_code { get; set; }
        public decimal sheet { get; set; }
        public decimal par_value { get; set; }
    }
}