// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class op_predata
    {
        public DateTime tran_date { get; set; }
        public string deal_no { get; set; }
        public string bill_no { get; set; }
        public string billno_description { get; set; }
        public string broker_code { get; set; }
        public string bank_account { get; set; }
        public decimal par_value { get; set; }
        public decimal buy_price { get; set; }
    }
}