// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class op_rate1
    {
        public string item_code { get; set; }
        public int? evaluation { get; set; }
        public decimal? rate { get; set; }
    }
}