// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class op_rate
    {
        public DateTime tran_date { get; set; }
        public int evaluation { get; set; }
        public decimal market_rate { get; set; }
    }
}