// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class portia_code
    {
        public string security { get; set; }
        public string price_symbol { get; set; }
    }
}