// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class reserch_source
    {
        /// <summary>
        /// 存取路徑
        /// </summary>
        public string reserch_source1 { get; set; }
        /// <summary>
        /// 存取代號
        /// </summary>
        public string rec_status { get; set; }
    }
}