// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class role_base
    {
        public string role_no { get; set; }
        public string role_name { get; set; }
    }
}