// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class role_prog
    {
        public string role_no { get; set; }
        public string sys_no { get; set; }
        public string prog_no { get; set; }
        public bool ins { get; set; }
        public bool del { get; set; }
        public bool mdf { get; set; }
        public bool qry { get; set; }
        public bool rpt { get; set; }
    }
}