// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class rp_base
    {
        public string bond_no { get; set; }
        public string bond_kind { get; set; }
        public string insure_type { get; set; }
        public string bond_alias { get; set; }
        public string bond_name { get; set; }
        public string issue_co { get; set; }
        public DateTime issue_date { get; set; }
        public decimal issue_period { get; set; }
        public decimal issue_amt { get; set; }
        public DateTime maturity_date { get; set; }
        public double coupon_rate { get; set; }
        public short int_times { get; set; }
        public short double_int_times { get; set; }
        public string capital_type { get; set; }
        public double? capital_year { get; set; }
        public double? capital_step { get; set; }
        public short? capital_part { get; set; }
        public string int_date { get; set; }
        public string insure_name { get; set; }
        public string main_order { get; set; }
        public string sk_code { get; set; }
        public string tax_type { get; set; }
        public string bond_no2 { get; set; }
        public decimal? tax_rate { get; set; }
        public string bond_no3 { get; set; }
        public string cancel_type { get; set; }
        public int? signetno { get; set; }
        public string bond_name2 { get; set; }
        public string bond_kind2 { get; set; }
        public string tran_type { get; set; }
        public string remark { get; set; }
        public string period_type { get; set; }
        public string rate_type { get; set; }
        public string int_date_first { get; set; }
        public string acccate { get; set; }
        public string unityid { get; set; }
        public string trade_market { get; set; }
    }
}