// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class rp_base_cb
    {
        public string bond_no { get; set; }
        public decimal? conv_price { get; set; }
        public decimal? conv_vol { get; set; }
        public DateTime? conv_s_date { get; set; }
        public DateTime? conv_e_date { get; set; }
        public decimal? call_yield_rate { get; set; }
        public DateTime? call_s_date { get; set; }
        public DateTime? call_e_date { get; set; }
        public decimal? rs_premium_rate { get; set; }
        public DateTime? rs_date { get; set; }
        public DateTime? last_cede_date { get; set; }
    }
}