// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class rp_cash
    {
        public string bond_no { get; set; }
        public DateTime pay_date { get; set; }
        public decimal i_amt { get; set; }
        public decimal c_amt { get; set; }
        public decimal m_amt { get; set; }
    }
}