// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class rpt_daily
    {
        public DateTime rpt_date { get; set; }
        public string rpt_acct { get; set; }
        public string ccy_type { get; set; }
        public string rpt_item { get; set; }
        public decimal rpt_amt { get; set; }
        public string rpt_dept { get; set; }
        public int marked { get; set; }
        public decimal seqno { get; set; }
        public string rpt_sys { get; set; }
        public string rpt_fund { get; set; }
        public string rpt_memo { get; set; }
        public string rpt_memo2 { get; set; }
    }
}