// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class rs_identable
    {
        public int key_col { get; set; }
        public string vouno { get; set; }
        public string key_right { get; set; }
    }
}