// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sb_billname
    {
        public string bill_name { get; set; }
        public string issue_unicode { get; set; }
    }
}