// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sb_broker
    {
        /// <summary>
        /// 券商總公司代號
        /// </summary>
        public string broker_co { get; set; }
        /// <summary>
        /// 券商分公司代號
        /// </summary>
        public string broker_code { get; set; }
        /// <summary>
        /// 券商名稱
        /// </summary>
        public string public_code { get; set; }
        /// <summary>
        /// 券商名稱
        /// </summary>
        public string broker_name { get; set; }
        /// <summary>
        /// 簡稱
        /// </summary>
        public string broker_alias { get; set; }
        /// <summary>
        /// 英文名稱
        /// </summary>
        public string broker_e_name { get; set; }
        /// <summary>
        /// 國別
        /// </summary>
        public string country_code { get; set; }
        /// <summary>
        /// 郵遞區號
        /// </summary>
        public string zip_code { get; set; }
        /// <summary>
        /// 住址
        /// </summary>
        public string broker_addr { get; set; }
        /// <summary>
        /// 電話
        /// </summary>
        public string broker_tel_no { get; set; }
        /// <summary>
        /// 傳真號碼
        /// </summary>
        public string broker_fax { get; set; }
        /// <summary>
        /// 是否為證券商
        /// </summary>
        public int? is_security_broker { get; set; }
        /// <summary>
        /// 是否為票券商
        /// </summary>
        public int? is_bill_broker { get; set; }
        /// <summary>
        /// 是否為銀行
        /// </summary>
        public int? is_bank { get; set; }
        /// <summary>
        /// 集保帳號
        /// </summary>
        public string broker_account { get; set; }
        /// <summary>
        /// 票券金額最高比率
        /// </summary>
        public decimal? max_rate { get; set; }
        /// <summary>
        /// 交割銀行代號
        /// </summary>
        public string bank_code { get; set; }
        /// <summary>
        /// 交割銀行帳號
        /// </summary>
        public string bank_account { get; set; }
        public string broker_id { get; set; }
        public string offten_use { get; set; }
        public int LIC_relat { get; set; }
        public int Financial_relat { get; set; }
        public string bank_code_self_out { get; set; }
        public string bank_account_self_out { get; set; }
        public string bank_code_self_in { get; set; }
        public string bank_account_self_in { get; set; }
        public string show_type { get; set; }
        public string bank_code_other_out { get; set; }
        public string bank_account_other_out { get; set; }
        public string print_memo_out { get; set; }
        public string bank_code_other_in { get; set; }
        public string bank_account_other_in { get; set; }
        public string print_memo_in { get; set; }
    }
}