// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sb_broker_list
    {
        public string sys_no { get; set; }
        public string fund_no { get; set; }
        public string broker_co { get; set; }
        public string broker_code { get; set; }
        public string bank_code1 { get; set; }
        public string bank_account1 { get; set; }
        public string bank_code2 { get; set; }
        public string bank_account2 { get; set; }
        public string name1 { get; set; }
        public string tel1 { get; set; }
        public string name2 { get; set; }
        public string tel2 { get; set; }
        public string fax { get; set; }
        public string bank_name1 { get; set; }
        public string bank_name2 { get; set; }
    }
}