// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sb_dtl
    {
        public short rec_status { get; set; }
        public string sys_no { get; set; }
        public string fund_no { get; set; }
        public string app_no { get; set; }
        public string dtl_no { get; set; }
        public DateTime bill_date { get; set; }
        public DateTime bill_enddate { get; set; }
        public string broker_code { get; set; }
        public string bill_type { get; set; }
        public string insure_name { get; set; }
        public decimal par_value { get; set; }
        public DateTime beg_date { get; set; }
        public DateTime end_date { get; set; }
        public string bill_name { get; set; }
        public decimal bill_rate { get; set; }
        public bool buy_cut { get; set; }
        public decimal buy_price { get; set; }
        public bool? relation { get; set; }
        public string bill_no { get; set; }
        public DateTime? cancel_date { get; set; }
        public int? marked { get; set; }
        public string org_app_no { get; set; }
    }
}