// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sb_hold
    {
        public DateTime holding_date { get; set; }
        public string broker_name { get; set; }
        public string bill_name { get; set; }
        public string end_date { get; set; }
        public string bill_date { get; set; }
        public string bill_enddate { get; set; }
        public string insure_name { get; set; }
        public decimal par_value { get; set; }
    }
}