// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sb_int
    {
        public string sys_no { get; set; }
        public string fund_no { get; set; }
        public string app_no { get; set; }
        public DateTime area_beg_date { get; set; }
        public DateTime area_end_date { get; set; }
        public short area_days { get; set; }
        public decimal area_int { get; set; }
        public decimal area_tax { get; set; }
    }
}