// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sb_register
    {
        public string sys_no { get; set; }
        public int year { get; set; }
        public string bank_id { get; set; }
        public decimal pay_amt { get; set; }
        public decimal pay_tax { get; set; }
        public decimal pay_net { get; set; }
        public int seqno { get; set; }
    }
}