// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sk_base
    {
        /// <summary>
        /// 股票代號
        /// </summary>
        public string sk_code { get; set; }
        /// <summary>
        /// 股票名稱
        /// </summary>
        public string sk_name { get; set; }
        public string acccate { get; set; }
        /// <summary>
        /// 股票類別(code_file.item_type = &apos;01&apos;)
        /// </summary>
        public string sk_type { get; set; }
        /// <summary>
        /// 總發行股數
        /// </summary>
        public decimal total_share { get; set; }
        /// <summary>
        /// 發行在外股數
        /// </summary>
        public decimal share_list { get; set; }
        /// <summary>
        /// 資本額
        /// </summary>
        public decimal cap_amt { get; set; }
        /// <summary>
        /// 除息日
        /// </summary>
        public DateTime? c_date { get; set; }
        /// <summary>
        /// 除息比例
        /// </summary>
        public double cash_dividend { get; set; }
        /// <summary>
        /// 除權日
        /// </summary>
        public DateTime? d_date { get; set; }
        /// <summary>
        /// 盈權比例
        /// </summary>
        public double stock_dividend { get; set; }
        /// <summary>
        /// 公配比例
        /// </summary>
        public double fund_dividend { get; set; }
        /// <summary>
        /// 現增日
        /// </summary>
        public DateTime? p_date { get; set; }
        /// <summary>
        /// 現增比例
        /// </summary>
        public double p_dividend { get; set; }
        /// <summary>
        /// 現增價格
        /// </summary>
        public decimal p_price { get; set; }
        /// <summary>
        /// 每股盈餘
        /// </summary>
        public decimal eps { get; set; }
        /// <summary>
        /// 產業別(code_file.item_type = &apos;02&apos;)
        /// </summary>
        public string buss_type { get; set; }
        /// <summary>
        /// 制別
        /// </summary>
        public string ccy { get; set; }
        public string tran_out { get; set; }
        /// <summary>
        /// 發行公司
        /// </summary>
        public string issue_co { get; set; }
        /// <summary>
        /// 印鑑章號碼
        /// </summary>
        public int? signet_no { get; set; }
        /// <summary>
        /// 淨值
        /// </summary>
        public decimal? mark_price { get; set; }
        /// <summary>
        /// 取用淨值(1 取用  0 不取用)
        /// </summary>
        public string is_get_price { get; set; }
        public string UnityID { get; set; }
        public decimal coupon_rate { get; set; }
    }
}