// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sk_capital
    {
        /// <summary>
        /// 建立日期
        /// </summary>
        public DateTime tran_date { get; set; }
        /// <summary>
        /// 資金數字
        /// </summary>
        public decimal capital_amt { get; set; }
        public string year_now { get; set; }
    }
}