// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sk_chgtype
    {
        /// <summary>
        /// 帳戶代號
        /// </summary>
        public string fund_no { get; set; }
        /// <summary>
        /// 轉型日
        /// </summary>
        public DateTime change_date { get; set; }
        /// <summary>
        /// 轉型別
        /// </summary>
        public string change_type { get; set; }
        /// <summary>
        /// 舊股代號
        /// </summary>
        public string sk_code_old { get; set; }
        /// <summary>
        /// 新股代踸
        /// </summary>
        public string sk_code_new { get; set; }
        /// <summary>
        /// 舊股股數
        /// </summary>
        public decimal volumn_old01 { get; set; }
        public decimal volumn_old02 { get; set; }
        /// <summary>
        /// 移轉成本
        /// </summary>
        public decimal net { get; set; }
        /// <summary>
        /// 新股股數
        /// </summary>
        public decimal volumn_new01 { get; set; }
        public decimal volumn_new02 { get; set; }
        /// <summary>
        /// 舊的型別
        /// </summary>
        public string sk_type_old { get; set; }
        /// <summary>
        /// 新的型別
        /// </summary>
        public string sk_type_new { get; set; }
        public string acccate { get; set; }
        public decimal? net_new { get; set; }
    }
}