// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sk_divid
    {
        /// <summary>
        /// 帳戶別
        /// </summary>
        public string fund_no { get; set; }
        /// <summary>
        /// 股票代號
        /// </summary>
        public string sk_code { get; set; }
        /// <summary>
        /// 除權除息日期
        /// </summary>
        public DateTime ex_date { get; set; }
        /// <summary>
        /// 當日持有股數
        /// </summary>
        public decimal hold_share { get; set; }
        /// <summary>
        /// 配股息比率(除權除息率)
        /// </summary>
        public decimal div_rate { get; set; }
        /// <summary>
        /// 配股股數(除權股數)
        /// </summary>
        public decimal? total_share { get; set; }
        /// <summary>
        /// 配息金額(除息金額)
        /// </summary>
        public decimal total_amt { get; set; }
        /// <summary>
        /// 所得稅率
        /// </summary>
        public float tax_rate { get; set; }
        /// <summary>
        /// 所得稅額
        /// </summary>
        public decimal tax_amt { get; set; }
        /// <summary>
        /// 應收淨額(除息淨額)
        /// </summary>
        public decimal net_amt { get; set; }
        /// <summary>
        /// 領股領息日
        /// </summary>
        public DateTime? recv_date { get; set; }
        /// <summary>
        /// 出售日
        /// </summary>
        public DateTime? sale_date { get; set; }
        /// <summary>
        /// 剩餘股數
        /// </summary>
        public decimal rem_volumn { get; set; }
        /// <summary>
        /// 交易別(1.除息2.盈配3.公配4.現增)
        /// </summary>
        public string action { get; set; }
        /// <summary>
        /// 實領金額(領取股數/金額)
        /// </summary>
        public decimal? rec_amt { get; set; }
        /// <summary>
        /// 交易編號
        /// </summary>
        public string recno { get; set; }
        /// <summary>
        /// 現增付款日
        /// </summary>
        public DateTime? pay_date { get; set; }
        /// <summary>
        /// 銀行代號
        /// </summary>
        public string bank_code { get; set; }
        /// <summary>
        /// 銀行帳號
        /// </summary>
        public string bank_account { get; set; }
        /// <summary>
        /// 集保帳號
        /// </summary>
        public string broker_account { get; set; }
        /// <summary>
        /// 郵費匯費
        /// </summary>
        public decimal? fee_amt { get; set; }
        /// <summary>
        /// 領取方式
        /// </summary>
        public string recv_kind { get; set; }
        /// <summary>
        /// 支票號碼
        /// </summary>
        public string check_no { get; set; }
        /// <summary>
        /// 溢配金額
        /// </summary>
        public decimal? over_dividend { get; set; }
        /// <summary>
        /// 溢配退還日
        /// </summary>
        public DateTime? return_date { get; set; }
        /// <summary>
        /// 溢配退還金額
        /// </summary>
        public decimal? return_amt { get; set; }
        /// <summary>
        /// 畸零股款
        /// </summary>
        public decimal? turn_cash { get; set; }
        /// <summary>
        /// 溢配退還方式
        /// </summary>
        public string recv_kind2 { get; set; }
        /// <summary>
        /// 溢配退還帳號
        /// </summary>
        public string bank_account2 { get; set; }
        /// <summary>
        /// 溢配退還支票號碼
        /// </summary>
        public string check_no2 { get; set; }
        public string acccate { get; set; }
        public decimal? over_int { get; set; }
        public decimal? pre_total_amt { get; set; }
    }
}