// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sk_dividdate
    {
        public string this_year { get; set; }
        public string sk_code { get; set; }
        public DateTime? set_date { get; set; }
    }
}