// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sk_divid_dtl
    {
        /// <summary>
        /// 帳戶別
        /// </summary>
        public string fund_no { get; set; }
        /// <summary>
        /// 股票代號
        /// </summary>
        public string sk_code { get; set; }
        /// <summary>
        /// 持有股數類別
        /// </summary>
        public string sys_type { get; set; }
        /// <summary>
        /// 除權除息日期
        /// </summary>
        public DateTime ex_date { get; set; }
        /// <summary>
        /// 券商代號
        /// </summary>
        public string broker_code { get; set; }
        /// <summary>
        /// 當日持有股數
        /// </summary>
        public decimal hold_share { get; set; }
        /// <summary>
        /// 配股息比率(除權除息率)
        /// </summary>
        public decimal div_rate { get; set; }
        /// <summary>
        /// 配股股數(除權股數)
        /// </summary>
        public decimal? total_share { get; set; }
        /// <summary>
        /// 配息金額(除息金額)
        /// </summary>
        public decimal total_amt { get; set; }
        /// <summary>
        /// 所得稅率
        /// </summary>
        public float tax_rate { get; set; }
        /// <summary>
        /// 所得稅額
        /// </summary>
        public decimal tax_amt { get; set; }
        /// <summary>
        /// 應收淨額(除息淨額)
        /// </summary>
        public decimal net_amt { get; set; }
        /// <summary>
        /// 領股領息日
        /// </summary>
        public DateTime? recv_date { get; set; }
        /// <summary>
        /// 交易別(除息(3-盈配;9-公配),除權(4-盈配;6公配),5-現增)
        /// </summary>
        public string action { get; set; }
        /// <summary>
        /// 實領金額(領取股數/金額)
        /// </summary>
        public decimal? rec_amt { get; set; }
        /// <summary>
        /// 交易編號
        /// </summary>
        public string recno { get; set; }
        /// <summary>
        /// 現增付款日
        /// </summary>
        public DateTime? pay_date { get; set; }
        /// <summary>
        /// 銀行代號
        /// </summary>
        public string bank_code { get; set; }
        /// <summary>
        /// 銀行帳號
        /// </summary>
        public string bank_account { get; set; }
        /// <summary>
        /// 郵費匯費
        /// </summary>
        public decimal? fee_amt { get; set; }
        /// <summary>
        /// 領取方式
        /// </summary>
        public string recv_kind { get; set; }
        /// <summary>
        /// 支票號碼
        /// </summary>
        public string check_no { get; set; }
        /// <summary>
        /// 溢配金額
        /// </summary>
        public decimal? over_dividend { get; set; }
        public string acccate { get; set; }
        public decimal? over_int { get; set; }
        public decimal pre_total_amt { get; set; }
        /// <summary>
        /// non-call是否有可扣抵稅額
        /// </summary>
        public short? taxfree_status { get; set; }
        /// <summary>
        /// 券商申報賣出股數
        /// </summary>
        public decimal del_share { get; set; }
        /// <summary>
        /// 領股息時對應sk_tran.tran_no
        /// </summary>
        public string recv_no { get; set; }
    }
}