// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sk_divid_dtl_p
    {
        public string fund_no { get; set; }
        public string sk_code { get; set; }
        public string sys_type { get; set; }
        public DateTime ex_date { get; set; }
        public string broker_code { get; set; }
        public decimal hold_share { get; set; }
        public decimal div_rate { get; set; }
        public decimal? total_share { get; set; }
        public decimal total_amt { get; set; }
        public float tax_rate { get; set; }
        public decimal tax_amt { get; set; }
        public decimal net_amt { get; set; }
        public DateTime? recv_date { get; set; }
        public string action { get; set; }
        public decimal? rec_amt { get; set; }
        public string recno { get; set; }
        public DateTime? pay_date { get; set; }
        public string bank_code { get; set; }
        public string bank_account { get; set; }
        public decimal? fee_amt { get; set; }
        public string recv_kind { get; set; }
        public string check_no { get; set; }
        public decimal? over_dividend { get; set; }
        public string acccate { get; set; }
        public decimal? over_int { get; set; }
        public decimal pre_total_amt { get; set; }
        public short? taxfree_status { get; set; }
        public decimal del_share { get; set; }
        public string recv_no { get; set; }
        public string broker_account { get; set; }
        public string sk_type { get; set; }
        public string p_code { get; set; }
        public string ex_chk_sales_id { get; set; }
        public DateTime? ex_chk_date { get; set; }
        public string recv_chk_sales_id { get; set; }
        public DateTime? recv_chk_date { get; set; }
    }
}