// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sk_dividinfo
    {
        /// <summary>
        /// 股票代號
        /// </summary>
        public string sk_code { get; set; }
        /// <summary>
        /// 除權日
        /// </summary>
        public DateTime? d_date { get; set; }
        /// <summary>
        /// 盈配比例
        /// </summary>
        public decimal stock_dividend { get; set; }
        /// <summary>
        /// 公配比例
        /// </summary>
        public decimal fund_dividend { get; set; }
        /// <summary>
        /// 除息日期
        /// </summary>
        public DateTime? c_date { get; set; }
        /// <summary>
        /// 除息比例
        /// </summary>
        public decimal cash_dividend { get; set; }
        /// <summary>
        /// 現增日期
        /// </summary>
        public DateTime? p_date { get; set; }
        /// <summary>
        /// 現增比例
        /// </summary>
        public decimal p_dividend { get; set; }
        /// <summary>
        /// 現增價格
        /// </summary>
        public decimal p_price { get; set; }
        /// <summary>
        /// 除權後新股本
        /// </summary>
        public decimal total_share { get; set; }
        /// <summary>
        /// 流水序號
        /// </summary>
        public decimal rec_no { get; set; }
        /// <summary>
        /// 交易狀態
        /// </summary>
        public bool? rec_status { get; set; }
        /// <summary>
        /// 股東會日期
        /// </summary>
        public DateTime? meeting_date { get; set; }
        /// <summary>
        /// 股息發放日
        /// </summary>
        public DateTime? c_recv_date { get; set; }
        /// <summary>
        /// 現增繳款截止日
        /// </summary>
        public DateTime? pay_end_date { get; set; }
        /// <summary>
        /// 股利發放日
        /// </summary>
        public DateTime? d_recv_date { get; set; }
        /// <summary>
        /// 現增股票發放日
        /// </summary>
        public DateTime? p_recv_date { get; set; }
        public decimal Surplus_dividend { get; set; }
        public DateTime? rights_date { get; set; }
        public DateTime? ins_date { get; set; }
        public string ins_op { get; set; }
    }
}