// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sk_dividpay
    {
        public string sk_code { get; set; }
        public string broker_code { get; set; }
        public string account { get; set; }
        public DateTime ex_date { get; set; }
        public DateTime? recv_date { get; set; }
        public decimal? hold_volumn { get; set; }
        public decimal? rate { get; set; }
        public decimal volumn { get; set; }
        public decimal? real_volumn { get; set; }
        public decimal price { get; set; }
        public decimal total_amt { get; set; }
        public decimal? real_totalamt { get; set; }
        public string bank_code { get; set; }
        public string bank_account { get; set; }
        public string check_no { get; set; }
        public DateTime? key_date { get; set; }
    }
}