// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sk_id
    {
        public string sk_code { get; set; }
        public string sk_name { get; set; }
        public string volumn { get; set; }
        public string tran_date { get; set; }
        public string sk_type { get; set; }
        public string unityID { get; set; }
    }
}