// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sk_ifrs_trans
    {
        public string fund_no { get; set; }
        public DateTime tran_date { get; set; }
        public string acc_type { get; set; }
        public string tran_no { get; set; }
        public string action { get; set; }
        public string sk_code { get; set; }
        public string broker_code { get; set; }
        public decimal? volumn { get; set; }
        public decimal? price { get; set; }
        public decimal? market_avg { get; set; }
        public decimal? market_tran { get; set; }
        public string p_code { get; set; }
    }
}