// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sk_inv
    {
        /// <summary>
        /// 帳戶別(fund_file.fund_no)
        /// </summary>
        public string fund_no { get; set; }
        /// <summary>
        /// 股票代號(sk_base.sk_code)
        /// </summary>
        public string sk_code { get; set; }
        /// <summary>
        /// 券商代號
        /// </summary>
        public string broker_code { get; set; }
        /// <summary>
        /// 1:現股,2:在途股
        /// </summary>
        public string broker_type { get; set; }
        /// <summary>
        /// 股數
        /// </summary>
        public decimal volumn { get; set; }
        /// <summary>
        /// 交易日期
        /// </summary>
        public DateTime tran_date { get; set; }
        /// <summary>
        /// 盈配股數
        /// </summary>
        public decimal? d_volumn { get; set; }
        /// <summary>
        /// 公配股數
        /// </summary>
        public decimal? f_volumn { get; set; }
    }
}