// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sk_plan
    {
        public string broker_code { get; set; }
        public DateTime? date { get; set; }
        public decimal? amount { get; set; }
        public decimal? rate { get; set; }
    }
}