// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sk_point
    {
        /// <summary>
        /// 交易日
        /// </summary>
        public DateTime tran_date { get; set; }
        /// <summary>
        /// 加權指數
        /// </summary>
        public decimal point { get; set; }
        public decimal otc_point { get; set; }
        public decimal etc_point { get; set; }
    }
}