// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sk_projectdividinfo
    {
        public string sk_code { get; set; }
        public string sk_name { get; set; }
        public DateTime? meeting_date { get; set; }
        public DateTime? Beg_Date { get; set; }
        public DateTime? End_Date { get; set; }
        public decimal? Cash_dividend { get; set; }
        public decimal? stock_volumn { get; set; }
        public decimal? fund_volumn { get; set; }
        public decimal? special_volumn { get; set; }
        public DateTime? notice_date { get; set; }
        public decimal? Surplus_dividend { get; set; }
        public DateTime? piny_date { get; set; }
    }
}