// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sk_report
    {
        /// <summary>
        /// 編號
        /// </summary>
        public string sn { get; set; }
        /// <summary>
        /// 交易日期
        /// </summary>
        public DateTime tran_date { get; set; }
        /// <summary>
        /// 會計分類
        /// </summary>
        public string acccate { get; set; }
        /// <summary>
        /// 股票類別
        /// </summary>
        public string sk_type { get; set; }
        /// <summary>
        /// 股票代號
        /// </summary>
        public string sk_code { get; set; }
        /// <summary>
        /// 代號中文說明
        /// </summary>
        public string sk_name { get; set; }
        /// <summary>
        /// 持有股數(期初)
        /// </summary>
        public decimal? beg_volumn { get; set; }
        /// <summary>
        /// 成本(期初)
        /// </summary>
        public decimal? beg_net { get; set; }
        /// <summary>
        /// 均價(期初)
        /// </summary>
        public decimal? beg_avgcost { get; set; }
        /// <summary>
        /// 發行股數(仟股)
        /// </summary>
        public decimal volumn { get; set; }
        /// <summary>
        /// 持股比例
        /// </summary>
        public decimal total_share { get; set; }
        /// <summary>
        /// 資金比例
        /// </summary>
        public decimal capital_amt { get; set; }
        /// <summary>
        /// 買進股數
        /// </summary>
        public decimal? in_volumn { get; set; }
        /// <summary>
        /// 其它成交股數(買進)
        /// </summary>
        public decimal? otherin_volumn { get; set; }
        /// <summary>
        /// 買進均價
        /// </summary>
        public decimal? in_avgprice { get; set; }
        /// <summary>
        /// 買進成本
        /// </summary>
        public decimal? in_cost { get; set; }
        /// <summary>
        /// 手續費
        /// </summary>
        public decimal? broker_comm { get; set; }
        /// <summary>
        /// 買進金額
        /// </summary>
        public decimal? in_amt { get; set; }
        /// <summary>
        /// 賣出股數
        /// </summary>
        public decimal? out_volumn { get; set; }
        /// <summary>
        /// 其它成交股數(賣出)
        /// </summary>
        public decimal? otherout_volumn { get; set; }
        /// <summary>
        /// 賣出均價
        /// </summary>
        public decimal? out_avgprice { get; set; }
        /// <summary>
        /// 賣出金額
        /// </summary>
        public decimal? out_amt { get; set; }
        /// <summary>
        /// 賣出總成本(含調整數)
        /// </summary>
        public decimal? out_cost { get; set; }
        /// <summary>
        /// 出售損益(含調整數)
        /// </summary>
        public decimal? gain_loss_2BE { get; set; }
        /// <summary>
        /// 現金股利
        /// </summary>
        public decimal? cash_dividend { get; set; }
        /// <summary>
        /// 已實現損益
        /// </summary>
        public decimal? gain_loss { get; set; }
        /// <summary>
        /// 持有股數(期末)
        /// </summary>
        public decimal? end_volumn { get; set; }
        /// <summary>
        /// 成本(期末)
        /// </summary>
        public decimal? end_net { get; set; }
        /// <summary>
        /// 均價(期末)
        /// </summary>
        public decimal? end_avgcost { get; set; }
        /// <summary>
        /// 收盤市價
        /// </summary>
        public decimal? market_price { get; set; }
        /// <summary>
        /// 總市值
        /// </summary>
        public decimal? market_net { get; set; }
        /// <summary>
        /// 未實現損益
        /// </summary>
        public decimal? non_gain_loss { get; set; }
        /// <summary>
        /// 備註(交易別)
        /// </summary>
        public string remark { get; set; }
    }
}