// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sk_skr009b
    {
        public decimal? pointA { get; set; }
        public decimal? pointB { get; set; }
        public decimal? pointC { get; set; }
        public decimal? acccate01A { get; set; }
        public decimal? acccate01B { get; set; }
        public decimal? acccate01C { get; set; }
        public decimal? acccate02A { get; set; }
        public decimal? acccate02B { get; set; }
        public decimal? acccate02C { get; set; }
        public int year { get; set; }
        public decimal? fundA { get; set; }
        public decimal? fundB { get; set; }
        public decimal? fundC { get; set; }
        public decimal? unlistedA { get; set; }
        public decimal? unlistedB { get; set; }
        public decimal? unlistedC { get; set; }
        public decimal? lkA { get; set; }
        public decimal? lkB { get; set; }
        public decimal? lkC { get; set; }
    }
}