// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sk_tranerr_memo
    {
        public string tran_no { get; set; }
        public string fund_no { get; set; }
        public string memo { get; set; }
    }
}