// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sk_total_ifrs9
    {
        public string fund_no { get; set; }
        public string sk_code { get; set; }
        public double? volumn { get; set; }
        public double? net { get; set; }
        public double? avg_cost { get; set; }
        public string acccate { get; set; }
    }
}