// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sk_total_p
    {
        public string fund_no { get; set; }
        public string sk_code { get; set; }
        public decimal volumn { get; set; }
        public decimal net { get; set; }
        public decimal avg_cost { get; set; }
        public DateTime tran_date { get; set; }
        public string sk_type { get; set; }
        public string acccate { get; set; }
        public string p_code { get; set; }
    }
}