// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sys_demand
    {
        /// <summary>
        /// 序號
        /// </summary>
        public string demand_no { get; set; }
        /// <summary>
        /// 單位
        /// </summary>
        public string department { get; set; }
        /// <summary>
        /// 異動項目
        /// </summary>
        public string item_no { get; set; }
        /// <summary>
        /// 系統別
        /// </summary>
        public string sys_no { get; set; }
        /// <summary>
        /// 需求提案日
        /// </summary>
        public DateTime tran_date { get; set; }
        /// <summary>
        /// 需求完成日
        /// </summary>
        public DateTime finish_date { get; set; }
        /// <summary>
        /// 需求提案人
        /// </summary>
        public string user_no { get; set; }
        /// <summary>
        /// 修改項目
        /// </summary>
        public string pro_no { get; set; }
        /// <summary>
        /// 需求說明
        /// </summary>
        public string memo { get; set; }
        /// <summary>
        /// 需求收件日
        /// </summary>
        public DateTime? tran_date2 { get; set; }
        /// <summary>
        /// 評估需求完成日
        /// </summary>
        public DateTime? finish_date2 { get; set; }
        /// <summary>
        /// 需求收件人
        /// </summary>
        public string user_no2 { get; set; }
        /// <summary>
        /// 評估異動項目
        /// </summary>
        public string item_no2 { get; set; }
        /// <summary>
        /// 處理狀況
        /// </summary>
        public string setup { get; set; }
        /// <summary>
        /// 新增日期
        /// </summary>
        public DateTime? keyin_date { get; set; }
        /// <summary>
        /// 新增時間
        /// </summary>
        public string keyin_time { get; set; }
        /// <summary>
        /// 修改日期
        /// </summary>
        public DateTime? modi_date { get; set; }
        /// <summary>
        /// 修改時間
        /// </summary>
        public string modi_time { get; set; }
        /// <summary>
        /// 補充說明
        /// </summary>
        public string memo2 { get; set; }
    }
}