// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sys_ftpconnect
    {
        public string name { get; set; }
        public string ip { get; set; }
        public string account { get; set; }
        public string pwd { get; set; }
        public string loguser { get; set; }
        public DateTime logtime { get; set; }
    }
}