// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sys_base
    {
        /// <summary>
        /// 系統編號
        /// </summary>
        public string sys_no { get; set; }
        /// <summary>
        /// 系統中文名稱
        /// </summary>
        public string sys_name { get; set; }
        /// <summary>
        /// 系統描述
        /// </summary>
        public string sys_desc { get; set; }
        /// <summary>
        /// 系統按鍵名稱
        /// </summary>
        public string sys_cmd { get; set; }
    }
}