// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sys_relationship
    {
        public string unityid { get; set; }
        public string unityname { get; set; }
        public string rbc { get; set; }
        public string relation_no { get; set; }
        public string company_group { get; set; }
        public string relation_behavior { get; set; }
        public string relation { get; set; }
    }
}