// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class sys_calendar
    {
        public DateTime work_date { get; set; }
        public DateTime tran_date { get; set; }
    }
}