// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class system_caw_transfer
    {
        public string item_type { get; set; }
        public string status { get; set; }
        public DateTime sys_date { get; set; }
    }
}