// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class system_file2
    {
        /// <summary>
        /// 帳務代號
        /// </summary>
        public string fund_no { get; set; }
        /// <summary>
        /// 系統代號
        /// </summary>
        public string sys_no { get; set; }
        /// <summary>
        /// 作帳時程
        /// </summary>
        public string sys_char { get; set; }
        /// <summary>
        /// 備註
        /// </summary>
        public string sys_memo { get; set; }
        /// <summary>
        /// 執行日期
        /// </summary>
        public DateTime? tran_date { get; set; }
        /// <summary>
        /// 執行時間
        /// </summary>
        public string tran_time { get; set; }
    }
}