// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class system_request
    {
        public string prog_no { get; set; }
        public DateTime get_date { get; set; }
        public DateTime request_time { get; set; }
        public string request_user { get; set; }
        public DateTime? excute_time { get; set; }
        public bool flag { get; set; }
    }
}