// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class system_File_fx
    {
        public string recno { get; set; }
        public string sys_name { get; set; }
        public string sys_char { get; set; }
        public DateTime last_date { get; set; }
        public DateTime sys_date { get; set; }
        public DateTime next_date { get; set; }
        public DateTime af_next_date { get; set; }
        public int prtserial { get; set; }
    }
}