// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class tas_lk_trans
    {
        public string trade_no { get; set; }
        public int pno { get; set; }
        public string fno { get; set; }
        public string code { get; set; }
        public DateTime trade_dt { get; set; }
        public short trade_tp { get; set; }
        public short cap_tp { get; set; }
        public string broker { get; set; }
        public decimal qty { get; set; }
        public string price_tp { get; set; }
        public DateTime beg_dt { get; set; }
        public DateTime end_dt { get; set; }
        public decimal rate { get; set; }
        public decimal avg_cost { get; set; }
        public decimal cost { get; set; }
        public decimal interest { get; set; }
        public decimal trans_fee { get; set; }
        public decimal service_fee { get; set; }
        public decimal tran_tax { get; set; }
        public string bank_accno { get; set; }
        public string TAS_org_trade_no { get; set; }
        public string TAS_tran_no { get; set; }
    }
}