// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class td_bkamt
    {
        public string fund_no { get; set; }
        public string bank_no { get; set; }
        public string branch_no { get; set; }
        public DateTime tran_date { get; set; }
        public decimal amount { get; set; }
        public string act_type { get; set; }
        public string memo { get; set; }
    }
}