// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class td_int_file
    {
        public bool rec_status { get; set; }
        public string fund_no { get; set; }
        public string deal_no { get; set; }
        public string period_type { get; set; }
        public string int_type { get; set; }
        public decimal capital { get; set; }
        public decimal int_rate { get; set; }
        public DateTime beg_date { get; set; }
        public DateTime end_date { get; set; }
        public DateTime? int_date { get; set; }
        public int actual_days { get; set; }
        public decimal interest { get; set; }
        public decimal tax { get; set; }
        public decimal net { get; set; }
        public DateTime? rec_date { get; set; }
        public decimal? recv_int { get; set; }
        public decimal? recv_tax { get; set; }
        public decimal? recv_net { get; set; }
    }
}