// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class td_report
    {
        public string sn { get; set; }
        public string deal_no { get; set; }
        public string acccate { get; set; }
        public string int_cont { get; set; }
        public string broker_name { get; set; }
        public DateTime? beg_date { get; set; }
        public DateTime? end_date { get; set; }
        public short? period_day { get; set; }
        public decimal? int_rate { get; set; }
        public string description { get; set; }
        public string act_type { get; set; }
        public decimal buy_capital { get; set; }
        public decimal sold_capital { get; set; }
        public decimal amts { get; set; }
        public decimal interest { get; set; }
        public decimal tax { get; set; }
        public decimal net { get; set; }
        public DateTime? rec_date { get; set; }
        public string td_no { get; set; }
        public string num { get; set; }
        public string loan_dept { get; set; }
        public string relation { get; set; }
    }
}