// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class tmp_FundData
    {
        public int Seq { get; set; }
        public string Product { get; set; }
        public string Ticker { get; set; }
        public string SecurityID { get; set; }
        public string ISIN { get; set; }
        public string CMoneyID { get; set; }
        public string CSName { get; set; }
        public string ESName { get; set; }
        public string CName { get; set; }
        public string EName { get; set; }
        public string FundType_LV1 { get; set; }
        public string FundType_LV2 { get; set; }
        public int? IssuerSeq { get; set; }
        public string IssuerTicker { get; set; }
        public string IssuerName { get; set; }
        public string OperateType { get; set; }
        public bool? IsEnable { get; set; }
        public string COUNTRY { get; set; }
        public string CNTRY_OF_RISK { get; set; }
        public string SevenRegions { get; set; }
        public string Currency { get; set; }
        public string VATNumber { get; set; }
        public bool? Rule12th { get; set; }
        public bool? IsClosePeriod { get; set; }
        public bool? Liquidity { get; set; }
        public string RaisingType { get; set; }
        public string OTC { get; set; }
        public string GIIN { get; set; }
        public string StkFAName { get; set; }
        public bool? IsIncomeFromUS { get; set; }
        public string FATCAStatus { get; set; }
        public string CertType { get; set; }
        public bool? IsIGAAnnexII { get; set; }
        public string Remark { get; set; }
        public string DepartmentID { get; set; }
        public DateTime? OfferingDate { get; set; }
        public bool? Is_FundUnit { get; set; }
        public string CreateUser { get; set; }
        public DateTime? CreateDT { get; set; }
        public string ModifyUser { get; set; }
        public DateTime? ModifyDT { get; set; }
        public DateTime? DisableDT { get; set; }
        public string memo { get; set; }
    }
}