// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class tmp_FundIssuer
    {
        public int UID { get; set; }
        public int? AMLInfoSeq { get; set; }
        public string IssuerArea { get; set; }
        public string Ticker { get; set; }
        public string ID_BB_Company { get; set; }
        public string CMoneyID { get; set; }
        public string Name { get; set; }
        public string Name_Chinese { get; set; }
        public string CreateUser { get; set; }
        public DateTime? CreateDT { get; set; }
        public string ModifyUser { get; set; }
        public DateTime? ModifyDT { get; set; }
        public bool? IsEnable { get; set; }
        public string FileGroupID { get; set; }
        public string DepID { get; set; }
        public string FatcaCode { get; set; }
        public string memo { get; set; }
    }
}