// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class tmp_cm_fund_nav
    {
        public DateTime ddate { get; set; }
        public string No { get; set; }
        public string Name { get; set; }
        public decimal? Nav { get; set; }
        public DateTime modifydate { get; set; }
        public string memo { get; set; }
    }
}