// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class tmp_fn_price
    {
        public string fn_no { get; set; }
        public decimal? price { get; set; }
        public DateTime? tran_date { get; set; }
        public decimal? tot_units { get; set; }
    }
}