// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class tmp_cm_fund_scalemper
    {
        public string YYYYMM { get; set; }
        public string No { get; set; }
        public string Name { get; set; }
        public decimal? Scale { get; set; }
        public decimal? Scale_Change { get; set; }
        public decimal? MarketShare { get; set; }
        public decimal? Pnav { get; set; }
        public decimal? TotalUnit_Million { get; set; }
        public decimal? TotalUnit { get; set; }
        public decimal? NaturalNum { get; set; }
        public decimal? LegalNum { get; set; }
        public decimal? TotalNum { get; set; }
        public decimal? Buy { get; set; }
        public decimal? Sell { get; set; }
        public decimal? Stsq_Num { get; set; }
        public decimal? Stsq_Person_Num { get; set; }
        public decimal? Stsq_Amt { get; set; }
        public int? ScaleRank { get; set; }
        public string FundType { get; set; }
        public decimal? Scale_Orig { get; set; }
        public decimal? Scale_Change_Orig { get; set; }
        public decimal? PNav_Orig { get; set; }
        public decimal? Buy_Orig { get; set; }
        public decimal? Sell_Orig { get; set; }
        public decimal? Stsq_Amt_Orig { get; set; }
        public string Currency { get; set; }
    }
}