// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class tmp_FundUnitsData
    {
        public int Seq { get; set; }
        public DateTime DataDate { get; set; }
        public string FundSeq { get; set; }
        public decimal? Units { get; set; }
        public string CreateUser { get; set; }
        public DateTime? CreateDT { get; set; }
        public string ModifyUser { get; set; }
        public DateTime? ModifyDT { get; set; }
        public bool? isDelete { get; set; }
        public decimal? Scale { get; set; }
        public string ScaleCurrency { get; set; }
    }
}