// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class tmp_Portfolio
    {
        public string FundID { get; set; }
        public string PAccount { get; set; }
        public string GTIAccount { get; set; }
        public string FundCode { get; set; }
        public string PortiaSymbol { get; set; }
        public string FundName { get; set; }
        public string FundSName { get; set; }
        public string FundLevel { get; set; }
        public string DepID { get; set; }
        public string DepTeamID { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string PolicyClass { get; set; }
        public string AccountType { get; set; }
        public string Currency { get; set; }
        public string SellingRule { get; set; }
        public string AssetStra { get; set; }
        public decimal? OPTMargin { get; set; }
        public bool? IsProfessional { get; set; }
        public string SettleType { get; set; }
        public string BondType_Lv1 { get; set; }
        public string FundCategory { get; set; }
        public string SettleGroup { get; set; }
        public string Custodian { get; set; }
        public string LendingAcc { get; set; }
        public string CreateUser { get; set; }
        public DateTime? CreateTime { get; set; }
        public string UpdateUser { get; set; }
        public DateTime? UpdateTime { get; set; }
        public string AssetClass { get; set; }
        public string InvestArea { get; set; }
        public string memo { get; set; }
    }
}