// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class tmp_cm_fund_dividend
    {
        public string No { get; set; }
        public string Name { get; set; }
        public string Currency { get; set; }
        public decimal? PUnitAmt { get; set; }
        public DateTime? StopTran_Sdate { get; set; }
        public DateTime? StopTran_Edate { get; set; }
        public DateTime? DividendDate { get; set; }
        public DateTime? Distribution_BaseDate { get; set; }
        public DateTime? Distribution_IssueDate { get; set; }
        public string DividendPeriod { get; set; }
        public string memo { get; set; }
    }
}