// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class tmp_fx_base
    {
        public string security_id { get; set; }
        public string secu_desc1 { get; set; }
        public decimal? cupon { get; set; }
        public DateTime? maturity { get; set; }
        public string isin { get; set; }
        public string security_type { get; set; }
    }
}