// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class tmp_r11
    {
        public string acccate { get; set; }
        public string sk_code { get; set; }
        public string sk_name { get; set; }
        public string sk_type { get; set; }
        public decimal beg_volumn { get; set; }
        public decimal? in_volumn { get; set; }
        public decimal? out_volumn { get; set; }
        public decimal end_volumn { get; set; }
        public decimal? total_share { get; set; }
        public decimal? holding_rate { get; set; }
        public decimal net { get; set; }
        public decimal? price { get; set; }
        public decimal? mkt_value { get; set; }
    }
}