// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class tmp_div1
    {
        public string rec_status { get; set; }
        public string deal_no { get; set; }
        public string fund_no { get; set; }
        public string fn_co { get; set; }
        public string fn_no { get; set; }
        public string acccate { get; set; }
        public DateTime tran_date { get; set; }
        public decimal tot_amt { get; set; }
        public decimal tot_unit { get; set; }
        public decimal unit_nav { get; set; }
        public decimal broker_fee { get; set; }
        public decimal bank_fee { get; set; }
        public decimal net { get; set; }
        public decimal fund_cost { get; set; }
        public decimal co_cost { get; set; }
        public decimal trust_unit { get; set; }
        public decimal confirm_unit { get; set; }
        public decimal newconfirm_unit { get; set; }
        public short dtl_status { get; set; }
        public string broker_code { get; set; }
        public decimal lcm_amt { get; set; }
        public string memo { get; set; }
        public string back_dealno { get; set; }
        public DateTime? trade_date { get; set; }
    }
}