// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class tmp_acdesc
    {
        public string gl { get; set; }
        public string acdesc { get; set; }
        public string _new { get; set; }
    }
}