// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class tmp_lend_portia
    {
        public string PORTFOLIO { get; set; }
        public double? TICKER { get; set; }
        public string SECURITY { get; set; }
        public string TranType { get; set; }
        public double? LOT { get; set; }
        public DateTime? Trade_Date { get; set; }
        public DateTime? Settle_Date { get; set; }
        public double? Quantity { get; set; }
        public double? PRICE { get; set; }
        public string __BROKER { get; set; }
        public string Under_Portfolio { get; set; }
        public DateTime? DATE { get; set; }
        public string TIME { get; set; }
    }
}