// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class tmp_FundIssuerRating
    {
        public DateTime ddate { get; set; }
        public string IssuerID { get; set; }
        public DateTime? LastUpdate { get; set; }
        public string RTG_SP_LT_FC_ISSUER_CREDIT { get; set; }
        public string RTG_SP_LT_LC_ISSUER_CREDIT { get; set; }
        public string RTG_MDY_ISSUER { get; set; }
        public string RTG_MOODY_LONG_TERM { get; set; }
        public string RTG_MDY_FC_CURR_ISSUER_RATING { get; set; }
        public string RTG_MDY_SEN_UNSECURED_DEBT { get; set; }
        public string RTG_FITCH_LT_ISSUER_DEFAULT { get; set; }
        public string RTG_FITCH_LT_FC_ISSUER_DEFAULT { get; set; }
        public string RTG_TRC_LONG_TERM { get; set; }
        public string RTG_FITCH_NATIONAL_LT { get; set; }
        public string memo { get; set; }
    }
}