// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class tmp_tb
    {
        public string fund_no { get; set; }
        public DateTime tran_date { get; set; }
        public string acccate { get; set; }
        public string sk_type { get; set; }
        public string sk_code { get; set; }
        public decimal? volumn { get; set; }
        public decimal capital_amt { get; set; }
        public decimal market_price { get; set; }
    }
}