// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class tmp_ets_fnd_trade
    {
        public string etl_trade_no { get; set; }
        public DateTime trade_dt { get; set; }
        public string fno { get; set; }
        public short seq { get; set; }
        public string fundcode { get; set; }
        public string isincode { get; set; }
        public string SecID { get; set; }
        public string SecName { get; set; }
        public string broker { get; set; }
        public short region { get; set; }
        public string ccy { get; set; }
        public bool IsPrepaid { get; set; }
        public short trade_tp { get; set; }
        public short deal_tp { get; set; }
        public decimal? qty { get; set; }
        public decimal? amt { get; set; }
        public decimal? nav { get; set; }
        public DateTime? nav_dt { get; set; }
        public decimal? tran_fee { get; set; }
        public decimal? tran_tax { get; set; }
        public decimal? commission { get; set; }
        public decimal? other_fee { get; set; }
        public decimal? exchange_fee { get; set; }
        public decimal? settle_amt { get; set; }
        public decimal? return_amt { get; set; }
        public DateTime? cash_value_dt { get; set; }
        public DateTime? act_value_dt { get; set; }
        public string bank_opp { get; set; }
        public string bank_branch { get; set; }
        public string bank_accno_opp { get; set; }
        public string bank_accno_name { get; set; }
        public decimal? hf_settle_amt { get; set; }
        public string lockuser { get; set; }
        public DateTime locktime { get; set; }
        public string lockuser2 { get; set; }
        public DateTime locktime2 { get; set; }
        public string manager { get; set; }
        public string approve { get; set; }
        public string trader { get; set; }
        public DateTime approve_dt { get; set; }
        public string approve_dep { get; set; }
        public DateTime approve_dep_dt { get; set; }
        public DateTime? act_trade_dt { get; set; }
        public DateTime decision_dt { get; set; }
        public DateTime decision_deal_dt { get; set; }
        public short market_type { get; set; }
        public string subtype { get; set; }
        public short stage { get; set; }
    }
}