// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class tmpg1
    {
        public string sys_no { get; set; }
        public string vou_type { get; set; }
        public string fund_no { get; set; }
        public string acccate { get; set; }
        public string invest_type { get; set; }
        public int amt_no { get; set; }
        public string gl { get; set; }
        public string sl1 { get; set; }
        public string vlife_gl { get; set; }
        public string acdesc { get; set; }
        public string drcr { get; set; }
        public string memo { get; set; }
        public int serial { get; set; }
    }
}