// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class tra_bnd_baladj
    {
        public string trade_no { get; set; }
        public DateTime trade_dt { get; set; }
        public int pno { get; set; }
        public string fno { get; set; }
        public string code { get; set; }
        public short cap_tp { get; set; }
        public decimal par_value { get; set; }
        public decimal cost { get; set; }
        public decimal acc_cost { get; set; }
        public decimal rl_cost_diff { get; set; }
        public decimal acc_rl_cost_diff { get; set; }
        public string crtuser { get; set; }
        public DateTime crttime { get; set; }
        public bool _lock { get; set; }
        public string lockuser { get; set; }
        public DateTime locktime { get; set; }
        public string loguser { get; set; }
        public DateTime logtime { get; set; }
    }
}