// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class tra_bnd_deal_rating
    {
        public string etl_trade_no { get; set; }
        public string fas_trade_no { get; set; }
        public string IssuedSPRating { get; set; }
        public string IssuedMoodysRating { get; set; }
        public string IssuedFitchRating { get; set; }
        public string IssuedTwnRating { get; set; }
        public string IssuedTwnFitchRating { get; set; }
        public string GuaranteeSPRating { get; set; }
        public string GuaranteeMoodysRating { get; set; }
        public string GuaranteeFitchRating { get; set; }
        public string GuaranteeTwnRating { get; set; }
        public string GuaranteeTwnFitchRating { get; set; }
        public string BondSPRating { get; set; }
        public string BondMoodysRating { get; set; }
        public string BondFitchRating { get; set; }
        public string BondTwnRating { get; set; }
        public string BondTwnFitchRating { get; set; }
        public DateTime IssuedGetRatingDate { get; set; }
        public DateTime GuaranteeGetRatingDate { get; set; }
        public DateTime BondGetRatingDate { get; set; }
        public string IssuedRating { get; set; }
        public string IssuedRatingType { get; set; }
        public string GuaranteeRating { get; set; }
        public string GuaranteeRatingType { get; set; }
        public string BondRating { get; set; }
        public string BondRatingType { get; set; }
        public bool IsCreditLosses { get; set; }
        public DateTime import_dt { get; set; }
    }
}