// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class user_prog
    {
        /// <summary>
        /// 使用者帳號(emp_base.sales_id)
        /// </summary>
        public string id_no { get; set; }
        /// <summary>
        /// 系統編號(sys_base.sys_no)
        /// </summary>
        public string sys_no { get; set; }
        /// <summary>
        /// 程式編號(prog_base.prog_no)
        /// </summary>
        public string prog_no { get; set; }
        /// <summary>
        /// 新增權限(1:yes 0:no)
        /// </summary>
        public bool ins { get; set; }
        /// <summary>
        /// 刪除權限(1:yes 0:no)
        /// </summary>
        public bool del { get; set; }
        /// <summary>
        /// 修改權限(1:yes 0:no)
        /// </summary>
        public bool mdf { get; set; }
        /// <summary>
        /// 查詢權限(1:yes 0:no)
        /// </summary>
        public bool qry { get; set; }
        /// <summary>
        /// 報表權限(1:yes 0:no)
        /// </summary>
        public bool rpt { get; set; }
    }
}