// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class user_sys
    {
        /// <summary>
        /// 使用者帳號(emp_base.sales_id)
        /// </summary>
        public string id_no { get; set; }
        /// <summary>
        /// 系統編號(sys_base.sys_no)
        /// </summary>
        public string sys_no { get; set; }
        /// <summary>
        /// 所有基金使用權限(1:yes 0:no)
        /// </summary>
        public bool manage { get; set; }
    }
}