// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class user_pwd_log
    {
        public string sales_id { get; set; }
        public DateTime chg_date { get; set; }
    }
}