// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class user_act_log
    {
        /// <summary>
        /// 使用者帳號(emp_base.sales_id)
        /// </summary>
        public string id_no { get; set; }
        /// <summary>
        /// 系統編號(sys_base.sys_no)
        /// </summary>
        public string sys_no { get; set; }
        /// <summary>
        /// 程式編號
        /// </summary>
        public string prog_no { get; set; }
        /// <summary>
        /// 執行日期
        /// </summary>
        public DateTime? login_date { get; set; }
        /// <summary>
        /// 執行時間
        /// </summary>
        public string login_time { get; set; }
        /// <summary>
        /// 回帳至那個時間
        /// </summary>
        public DateTime? restore_date { get; set; }
        /// <summary>
        /// 目前做程時間
        /// </summary>
        public DateTime? system_date { get; set; }
        /// <summary>
        /// 執行的基金代號
        /// </summary>
        public string fund_no { get; set; }
    }
}