// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class vl_bankacct_sl2
    {
        public string bank_acct { get; set; }
        public string sl2 { get; set; }
        public string sl2_memo { get; set; }
        public int policy_acct { get; set; }
    }
}