// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class vl_fee_base
    {
        public string fee_gl { get; set; }
        public string sys_no { get; set; }
        public string dept_name { get; set; }
        public string f_code { get; set; }
    }
}