// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class vl_gl_group
    {
        public string sys_no { get; set; }
        public string group_seq { get; set; }
        public string group_name { get; set; }
        public string vou_type { get; set; }
        public int serial { get; set; }
        public string dept_name { get; set; }
        public string flag { get; set; }
        public string vlife_code { get; set; }
    }
}