// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class vl_gl_trans
    {
        public string sys_no { get; set; }
        public DateTime? sys_date { get; set; }
        public int batch_no { get; set; }
        public DateTime? vou_date { get; set; }
        public string vou_type { get; set; }
        public string fund_no { get; set; }
        public int? acct_seq { get; set; }
        public string acccate { get; set; }
        public string invest_type { get; set; }
        public string bank_acct { get; set; }
        public decimal? amt1 { get; set; }
        public string memo1 { get; set; }
        public decimal? amt2 { get; set; }
        public string memo2 { get; set; }
        public decimal? amt3 { get; set; }
        public string memo3 { get; set; }
        public decimal? amt4 { get; set; }
        public string memo4 { get; set; }
        public decimal? amt5 { get; set; }
        public string memo5 { get; set; }
        public decimal? amt6 { get; set; }
        public string memo6 { get; set; }
        public decimal? amt7 { get; set; }
        public string memo7 { get; set; }
        public decimal? amt8 { get; set; }
        public string memo8 { get; set; }
        public decimal? amt9 { get; set; }
        public string memo9 { get; set; }
        public decimal? amt10 { get; set; }
        public string memo10 { get; set; }
        public string order_no { get; set; }
        public string dept_name { get; set; }
        public string emp { get; set; }
        public string ccy_type { get; set; }
        public DateTime? r_date { get; set; }
        public int oiu { get; set; }
    }
}