// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class vl_mafAR_Fx_tmp
    {
        public string fund_no { get; set; }
        public DateTime vou_date { get; set; }
        public string ccy_type { get; set; }
        public string bank_acct_in { get; set; }
        public string bank_acct_out { get; set; }
        public string deal_no { get; set; }
        public string drcr { get; set; }
        public decimal amt { get; set; }
        public string memo { get; set; }
        public string batch_no { get; set; }
        public string ccy_type2 { get; set; }
        public decimal amt2 { get; set; }
        public string cash_item { get; set; }
        public string sys_no { get; set; }
        public string emp { get; set; }
        public int? seq_no { get; set; }
    }
}