// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class vl_mafAR_detail
    {
        public DateTime vou_date { get; set; }
        public string batch_no { get; set; }
        public string deal_no { get; set; }
        public string sys_no { get; set; }
        public string r_code { get; set; }
        public string drcr { get; set; }
        public decimal? amt1 { get; set; }
        public decimal amt2 { get; set; }
        public string bank_acct { get; set; }
        public string memo { get; set; }
        public string cash_item { get; set; }
        public int seqno { get; set; }
        public string dtl_status { get; set; }
    }
}