// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class vl_maf10_upload
    {
        public string co_fund_no { get; set; }
        public string fund_no { get; set; }
        public string vouno { get; set; }
        public int rownum { get; set; }
        public DateTime vou_date { get; set; }
        public string gl { get; set; }
        public string sl { get; set; }
        public string f_code { get; set; }
        public string cost_unit { get; set; }
        public string path { get; set; }
        public decimal amt { get; set; }
        public string ccy_type { get; set; }
        public string memo { get; set; }
        public string r_code { get; set; }
        public string ifrs17_group { get; set; }
        public string crtuser { get; set; }
        public string relate_role { get; set; }
        public string relate_tp { get; set; }
        public string acccate_rule { get; set; }
        public string system_tp { get; set; }
        public string batch_no { get; set; }
    }
}