// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class vl_maf01_ifrs9
    {
        public string gl_ias39 { get; set; }
        public string acdesc_ias39 { get; set; }
        public string gl_ifrs9 { get; set; }
        public string acdesc_ifrs9 { get; set; }
        public string memo { get; set; }
    }
}