// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class vl_maf10
    {
        public string fund_no { get; set; }
        public DateTime vou_date { get; set; }
        public string vlife_code { get; set; }
        public string vounoA { get; set; }
        public int rownumA { get; set; }
        public string vounoB { get; set; }
        public int rownumB { get; set; }
        public string ccy_type { get; set; }
        public string gl { get; set; }
        public string sl1 { get; set; }
        public string sl2 { get; set; }
        public string r_code { get; set; }
        public string drcr { get; set; }
        public decimal amt { get; set; }
        public string memo { get; set; }
        public string sys_no { get; set; }
        public string dept_name { get; set; }
        public string group_seq { get; set; }
        public string group_name { get; set; }
        public string vou_source { get; set; }
        public string emp { get; set; }
        public DateTime ins_date { get; set; }
        public string f_code { get; set; }
        public string fx_vounoB { get; set; }
        public int? fx_rownumB { get; set; }
        public int? oiu { get; set; }
    }
}