// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class vl_maf01_len8
    {
        public string gl { get; set; }
        public string acdesc { get; set; }
        public string type { get; set; }
        public int r_code { get; set; }
    }
}