// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class vl_總帳科目停用清單
    {
        public string gl { get; set; }
        public string acdesc { get; set; }
    }
}