// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class vl_總帳調整科目對照
    {
        public string gl_new { get; set; }
        public string acdesc_new { get; set; }
        public string gl_old { get; set; }
        public string acdesc_old { get; set; }
    }
}