// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class wk_ets_stk_trade
    {
        public DateTime ddate_w { get; set; }
        public string ifund { get; set; }
        public string istkid { get; set; }
        public string iagtid { get; set; }
        public string ftype { get; set; }
        public decimal? price { get; set; }
        public decimal? qstks { get; set; }
        public string icurid { get; set; }
        public decimal? mtotal { get; set; }
        public decimal? mfee { get; set; }
        public decimal? mtax { get; set; }
        public decimal? msum { get; set; }
        public DateTime? dsato_w { get; set; }
        public string fsource { get; set; }
        public decimal? Charges { get; set; }
        public string stktype { get; set; }
        public decimal? Commission { get; set; }
        public string RefNo { get; set; }
        public string DecManegeName { get; set; }
        public string DecAuditName { get; set; }
        public DateTime? DecAuditDT { get; set; }
        public string OrderTraderName { get; set; }
    }
}