// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CashManagement.Entity
{
    public partial class wk_sb_trans
    {
        public string action { get; set; }
        public string sys_no { get; set; }
        public string fund_no { get; set; }
        public DateTime tran_date { get; set; }
        public string app_no { get; set; }
        public DateTime beg_date { get; set; }
        public DateTime end_date { get; set; }
        public short buy_days { get; set; }
        public string broker_code { get; set; }
        public string bill_type { get; set; }
        public decimal par_value { get; set; }
        public decimal buy_price { get; set; }
        public decimal buy_rate { get; set; }
        public decimal buy_int { get; set; }
        public decimal buy_tax { get; set; }
        public decimal sold_price { get; set; }
        public DateTime? cancel_date { get; set; }
        public short? act_days { get; set; }
        public decimal? act_rate { get; set; }
        public decimal? act_int { get; set; }
        public decimal? act_tax { get; set; }
        public decimal? act_price { get; set; }
        public short settle_status { get; set; }
        public string bill_no { get; set; }
        public bool? buy_cut { get; set; }
        public bool? relation { get; set; }
        public short? buymonth { get; set; }
        public short? buydate { get; set; }
        public string acccate { get; set; }
        public string org_app_no { get; set; }
        public string source_deal_no { get; set; }
        public DateTime? roll_in_date { get; set; }
        public string Acount { get; set; }
        public string AcountName { get; set; }
    }
}